[feat][#7] timeAxisView 와이어프레임
DeveloperAcademy-POSTECH/MacC-Team15-Ampersand pull request #20
Opened 2023-10-05 12:38 UTC by abovocado

# Description
close [#7 ]
timeAxisView의 와이어프레임을 구현했습니다.

- 캘린더 권한 설정.
- 캘린더에서 공휴일 정보를 받아오고 뷰에 표시합니다.
- 좌, 우 스크롤 할 때마다 최 좌측이 몇 월인지 동적으로 보여줍니다.
- x축으로 Scroll된 값을 계산하는 스크롤뷰를 구현했습니다.

# Screenshots & Demo
[Optional] 개발한 기능의 스크린샷이나 gif, 영상

https://github.com/DeveloperAcademy-POSTECH/MacC-Team15-Ampersand/assets/102544840/c4690282-05ee-4071-9a97-4ed444a7db47

# To Reviewers 🤲
- [ ] @OreobrO ScrollViewReader 의 proxy를 사용하기 위해 전체 코드에서 저의 ObservableScrollView를 적용해야 합니다.
- [ ] @OreobrO 확대/축소에 따라 변하는 DayGridView의 너비값을 적용해야 합니다!

2023-10-05 12:58 UTC, OreobrO approved these changes
승인합니다.

2023-10-05 13:42 UTC, xnoag approved these changes
승인합니다.

2023-10-05 14:11 UTC, dayo2n requested changes

2023-10-05 14:11 UTC, dayo2n commented on gridy/Sources/Models/DateInfo.swift
> +     }
dayOfweek는 값이 한정되어있기 때문에 Stirng보다는 Enum 타입으로 선언해서 사용하는 게 좋아요
String은 오타의 위험도 있지만 타입을 선언해서 사용하면 정확히 뭘 의미하는지, 어떤 값을 갖는지 알기 쉬워서 코드 관리가 쉬워집니다

```
enum DayOfWeek: String {
    case monday = "월"
    case tuesday = "화"
    case wednesday = "수"
    // ... 이하 생략
}
```

위 코드처럼 선언하고 이니셜라이저에서 파싱한 date 값으로부터 dayOfWeek 프로퍼티를 초기화해줄 땐 `self.dayOfWeek = DayOfWeek(rawValue: self.date.dayOfWeek)!`으로 쓸 수 있겠네요

+ 추가로 헨리가 현지화를 고려하고 있어서 나중에 수정하기에도 용이할 것 같아요!

2023-10-05 14:11 UTC, dayo2n commented on gridy/Sources/Presentations/PlanBoard/TimelineLayout/TimeAxisArea/DayGridView.swift
> +
필요없는 개행 X

2023-10-05 14:11 UTC, dayo2n commented on gridy/Sources/Presentations/PlanBoard/TimelineLayout/TimeAxisArea/DayGridView.swift
> +                    .overlay(Rectangle().stroke(Color.black, lineWidth: 0.3).frame(height: 1), alignment: .bottom)
인자가 두 개 이상인 경우 괄호와 인자마다 개행하기로 했는데 도트에도 각각 개행하면 좋겠어요!!
가독성이 떨어져서 알아보기가 어려워요

2023-10-05 14:11 UTC, dayo2n commented on gridy/Sources/Presentations/PlanBoard/TimelineLayout/TimeAxisArea/ObservableScrollView.swift
> +                    })
✅ 39번째줄 GeometryReader 이전 개행 확인

2023-10-05 14:11 UTC, dayo2n commented on gridy/Sources/Presentations/PlanBoard/TimelineLayout/TimeAxisArea/TimeAxisAreaView.swift
> +    @State private var leftmostDate: Date = Date()
코드 컨벤션 중 생략 가능한 코드는 작성하지 않는다: Date()로 초기화하면서 타입 추론이 가능해요!

2023-10-05 14:12 UTC, dayo2n commented
실행해보니까 저는 이렇게 보이는데 지금 진행상황까지는 이게 맞는건가요 ?!
<img width="2032" alt="스크린샷 2023-10-05 오후 10 50 47" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team15-Ampersand/assets/57654681/5011c277-d92c-4cc6-8c31-014a84c6ae40">

2023-10-05 14:26 UTC, abovocado commented on gridy/Sources/Presentations/PlanBoard/TimelineLayout/TimeAxisArea/DayGridView.swift
> +
개행 확인 후 삭제했습니다 😇

2023-10-05 14:26 UTC, abovocado commented on gridy/Sources/Models/DateInfo.swift
> +         self.isHoliday = isHoliday
개행 확인 후 삭제 완료했습니다😇

2023-10-05 14:26 UTC, abovocado commented on gridy/Sources/Presentations/PlanBoard/TimelineLayout/TimeAxisArea/DayGridView.swift
> +                    .overlay(Rectangle().stroke(Color.black, lineWidth: 0.3).frame(height: 1), alignment: .bottom)
확인 후 개행 완료했습니다 😇

2023-10-05 14:27 UTC, abovocado commented on gridy/Sources/Presentations/PlanBoard/TimelineLayout/TimeAxisArea/TimeAxisAreaView.swift
> +    @State private var leftmostDate: Date = Date()
확인 후 코드 삭제 완료했습니다 😇

2023-10-05 14:27 UTC, abovocado commented on gridy/Sources/Extensions/Date+Extension.swift
> +
확인 후 개행 삭제했습니다 😇

2023-10-05 14:29 UTC, abovocado commented on 1
> +# Lines starting with '#' will be ignored, and an empty message aborts # the commit.
파일 삭제 완료했습니다 😇

2023-10-06 00:31 UTC, abovocado commented on gridy/Sources/Presentations/PlanBoard/TimelineLayout/TimeAxisArea/ObservableScrollView.swift
> +                    })
확인후 개행 완료했습니다😇

2023-10-06 00:41 UTC, abovocado commented on gridy/Sources/Models/DateInfo.swift
> +     }
😇

2023-10-06 01:39 UTC, dayo2n approved these changes

2023-10-06 01:39 UTC, merged