[feat][#11] Sign in with Apple
DeveloperAcademy-POSTECH/MacC-Team15-Ampersand pull request #23
Opened 2023-10-05 17:25 UTC by dayo2n

# Description
close #11
애플로 로그인 기능을 개발했습니다

# Screenshots & Demo
![ezgif com-video-to-gif (2)](https://github.com/DeveloperAcademy-POSTECH/MacC-Team15-Ampersand/assets/57654681/3f54287c-07c8-45b3-b2c9-8f28195e01c1)

# To Reviewers 🤲
- [ ] 리드미나 주석 등 간간히 해당 이슈와 상관없는 수정이 있습니다.
- [ ] 한 번 가입한 후에는 자동으로 로그인되도록 했습니다. 
- [ ] @xnoag 과 함께 작업했습니다. 샤라웃 투 개스라이팅온
- [ ] 로그아웃 기능은 API 호출한 함수만 있고, 아직 실제로 호출되는 부분은 없습니다. 로그아웃은 꽤 복잡한 로직이 필요해서 천천히 구현하겠습니다 (앱스토어 출시쯤 ...)

2023-10-07 07:49 UTC, OreobrO requested changes
- 오타수정: encrytedNonce > encryptedNonce

- 오류수정: Apple로 로그인 버튼이 본인이 속한 뷰 크기 전체를 잡아먹는 현상_ Demo는 정상 작동 하는 것을 보면, 아래 기타에 명기해놓은 문제와 연관된 것이 아닌가 생각도 듭니다.

- 이미지교체: Logo, LogoBackground 이미지를 iCloud에 새로이 파일을 두었습니다. 해당 파일로 교체 요청드려요.

- 제안: clipshape가 필요한 부분에 당장 해결할 수 있는 방식의 코드 제안 해두었습니다. 자주 필요한 형태의 배경이라면 커스텀뷰를 만드는 것도 추후 고려 가능

- 기타: 현재 Team이 UnknownName으로 되어있어서 그런가, app Capability에 SignInWithApple을 추가할 수 없는 상태로, 확인 부탁드립니다.

2023-10-07 07:49 UTC, OreobrO commented on gridy/Sources/ContentView.swift
> +                        .background {
.background {
                            Rectangle()
                                .foregroundColor(.gray.opacity(0.1))
                                .mask(
                                    ZStack {
                                        RoundedRectangle(cornerRadius: 30)
                                        Rectangle()
                                            .offset(y: 30)
                                    }
                                )

2023-10-07 07:49 UTC, OreobrO commented on gridy/Sources/ContentView.swift
> +                        .background {
이 방법도 제안해 봅니다. mask영역에 포함되기 때문에 offset된 값에 의해 뷰가 커지지 않고 클립된 형태로 표현 가능

2023-10-07 07:49 UTC, OreobrO commented on gridy/Resources/Assets.xcassets/background/gridBackground.imageset/gridBackground.png
iCloud / AMPERSAND / Develop-asset/Logo
위 폴더에 1, 2, 3배 이미지 에셋을 정리해두었으니, 해당 에셋으로 변경 요청드려요

2023-10-07 07:49 UTC, OreobrO commented on gridy/Resources/Assets.xcassets/gridy-logo.imageset/gridy-logo.png
iCloud / AMPERSAND / Develop-asset/Logo
위 폴더에 1, 2, 3배 이미지 에셋을 정리해두었으니, 해당 에셋으로 변경 요청드려요

2023-10-07 07:49 UTC, OreobrO commented on gridy/Sources/Presentations/Authentication/AuthenticationView.swift
> +                    request.nonce = viewStore.encrytedNonce
encrytedNonce > encryptedNonce
오타 수정 필요합니다.

2023-10-07 07:49 UTC, OreobrO commented on gridy/Sources/Presentations/Authentication/Authentication.swift
> +        var encrytedNonce = ""
encrytedNonce > encryptedNonce 오타 수정 필요합니다.

2023-10-07 07:49 UTC, OreobrO commented on gridy/Sources/Presentations/Authentication/AuthenticationView.swift
> +                        // TODO: completion handler도 Reducer에서 처리해야 할까요? -ZEN
나중에 다른 로그인 방식이 들어올 경우를 생각한다면, 애플로 로그인 버튼의 completion handler도 Reducer에서 처리하는게 좋을 듯합니다. 당장은 높은 우선순위는 아니겠지만...

2023-10-07 07:49 UTC, OreobrO commented on gridy/Sources/Presentations/Authentication/AuthenticationView.swift
> +                    request.nonce = viewStore.encrytedNonce
encryted 검색해서 나오는 부분들 동일 수정

2023-10-07 07:49 UTC, OreobrO commented on gridy/Sources/Presentations/Authentication/AuthenticationView.swift
> +                SignInWithAppleButton(.signIn) { request in
SignInWithAppleButton이 본인이 속한 뷰의 크기 전체를 항상 잡아먹는 형태로 렌더링이 되는데, 해당 문제 해결 방법을 찾아야할 듯 합니다.

2023-10-07 09:40 UTC, dayo2n commented on gridy/Sources/ContentView.swift
> +                        .background {
xcode를 업데이트함에 따라 Shape.rect()를 사용하는 것으로 변경했습니다
macOS 13.0+ 지원!

코멘트남길 때 리뷰를 남기려는 영역을 드래그해서 포함할 수 있어요! 지금은 .background코드만 보이네요 TT
그리고 코드를 남길 때는 벡틱(`)으로 코드 영역을 만들어 주면 보기 좋을 것 같습니닷 👀

2023-10-07 09:49 UTC, dayo2n commented on gridy/Sources/Presentations/Authentication/AuthenticationView.swift
> +                        // TODO: completion handler도 Reducer에서 처리해야 할까요? -ZEN
#25 에서 처리하겠습니다~!~

2023-10-07 10:06 UTC, dayo2n commented on gridy/Sources/Presentations/Authentication/AuthenticationView.swift
> +                SignInWithAppleButton(.signIn) { request in
sonoma 업데이트되면서 AppKit에서 생긴 버그같아요 버그인지 변경된 사항인지는 모르겠지만!
clipShape를 같이 써줘야 frame 사이즈 지정이 가능하다네요 수정완료했습니닷
그리고 헨리가 카톡으로 알려준 capability에서 sign in with apple 항목이 추가되지 않는 이유는, entitlements에 소스 컨플릭트가 있었는데 이상하게 빌드는 성공적으로 되어서 발견하지 못했네요 이것도 수정 완료해서 동작하는거 확인했습니다 ~~
<img width="639" alt="스크린샷 2023-10-07 오후 7 02 35" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team15-Ampersand/assets/57654681/e4aa67e3-0ec3-49eb-a9af-c9ecc31922a7">

2023-10-07 10:11 UTC, OreobrO commented on gridy/Sources/ContentView.swift
> +                        .background {
```
이렇게 하는군요~
```

2023-10-07 10:15 UTC, OreobrO commented on gridy/Sources/Presentations/Authentication/AuthenticationView.swift
> +                SignInWithAppleButton(.signIn) { request in
추가된 부분 확인했습니다!

2023-10-07 10:22 UTC, OreobrO requested changes
제나, <Encrypted: 암호화된> 철자에서 P가 빠졌어요!

2023-10-07 10:22 UTC, OreobrO commented on gridy/Sources/Presentations/Authentication/AuthenticationView.swift
> +                    request.nonce = viewStore.encrytedNonce
제나, <Encrypted: 암호화된> 철자에서 P가 전부 빠졌어요!

2023-10-07 10:26 UTC, dayo2n commented on gridy/Sources/Presentations/Authentication/AuthenticationView.swift
> +                    request.nonce = viewStore.encrytedNonce
고마워여 헨리!! 진짜 다 수정했어요....!!! 아마도 ... 리얼루다가 .....

2023-10-07 10:27 UTC, OreobrO approved these changes
확인했습니다. 고생하셨어요 제나!

2023-10-07 10:31 UTC, dayo2n commented
악 커밋메시지 오타났다 ............... !!

2023-10-07 10:46 UTC, xnoag requested changes
1. 처음에 애플로 로그인 잘 작동해요.
2. 한 번 더 실행했을 때는 자동으로 로그인이 돼요.
3. <gridy/Sources/gridyApp.swift> //TimelineLayoutView 주석은 지우는 건 어때용?

2023-10-08 06:17 UTC, xnoag approved these changes
고마워요 제나 !~!

2023-10-08 06:17 UTC, merged