Feat/24 timeaxisview
DeveloperAcademy-POSTECH/MacC-Team15-Ampersand pull request #26
Opened 2023-10-10 08:38 UTC by abovocado

# Description
close [#24]
TimeAxisView의 세부 기능을 개발했습니다.
- 오늘 날짜에 빨간 박스
- 날짜 누르면 해당 날짜를 최좌측으로 이동
- DatePicker로 날짜 선택하면 해당 날짜를 최좌측으로 이동
- proxy 공유
- 날짜 자체를 index로 인식하도록 date를 integer로 변환

# Screenshots & Demo
[Optional] 개발한 기능의 스크린샷이나 gif, 영상

https://github.com/DeveloperAcademy-POSTECH/MacC-Team15-Ampersand/assets/102544840/d0f516e7-abe1-43a5-88c0-264bac322df2

# To Reviewers 🤲
- [ ] @OreobrO  animation 못넣었어요... 날짜 로드하는 기능도,,, 추후 작업 예정

2023-10-10 11:16 UTC, xnoag approved these changes
코드 다 확인했고, 오타 없습니다.
시뮬레이터도 잘 동작합니다! 릴리를 승인합니다.

2023-10-10 19:14 UTC, dayo2n requested changes
릴라이 최고 🙌🤩👒 넘 수고해써여 ~~~

2023-10-10 19:14 UTC, dayo2n commented on gridy/Sources/Extensions/Date+Extension.swift
>  }
생략 가능한 코드는 사용하지 않습니다!
요기 두 프로퍼티는 리턴 코드를 생략해주세요 🤓

2023-10-10 19:14 UTC, dayo2n commented on gridy/Sources/Presentations/PlanBoard/TimelineLayout/RightToolBarArea/ScrollDatePickerView.swift
> +            })
버튼의 action이 외부에서 정의된 클로저가 아니라면 [trailing closure](https://www.hackingwithswift.com/sixty/6/5/trailing-closure-syntax)로 작성해요!
괄호 사용을 최소화하면 코드 읽기가 수월해집니다
```swift
Button {
  // action
} label : {
  // label 
}
```

2023-10-10 19:14 UTC, dayo2n commented on gridy/Sources/Presentations/PlanBoard/TimelineLayout/TimeAxisArea/ObservableScrollView.swift
> +//        .coordinateSpace(name: scrollSpace)
나중에 사용되어야 해서 남아있는 코드겠죠 ?!

2023-10-10 19:14 UTC, dayo2n commented on gridy/Sources/Presentations/PlanBoard/TimelineLayout/TimeAxisArea/TimeAxisAreaView.swift
>      @State private var holidays: [Date] = []
```suggestion
    @State private var holidays = [Date]()
```
이렇게 초기화하면 타입추론이 가능해지니 타입을 명시하지 않아도 되어요! 
지금 코드도 좋아서 요기 수정은 옵셔널!입니다!

2023-10-10 19:30 UTC, dayo2n commented on gridy/Sources/Presentations/PlanBoard/TimelineLayout/RightToolBarArea/ScrollDatePickerView.swift
> +            })
```suggestion
            Button(action: buttonAction) {
                Text("이동")
            })
            
            // body 밖에서
            private func buttonAction() {
                    withAnimation {
                            let scrollIndex = selectedDate.integerDate
                            proxy?.scrollTo(scrollIndex, anchor: .leading)
                    }
            }
```

버튼이라서 action에 대한 클로저를 분리해서 사용하는 것도 좋겠습니다
버튼에 대한 동작이 많아지면 함수에서만 수정하면 돼서 유지보수에도 좋을 것 같고,
label에 대해서는 trailing closure로 작성할 수도 있어 가독성도 좋아지네요

2023-10-11 01:17 UTC, abovocado commented on gridy/Sources/Extensions/Date+Extension.swift
>  }
완료 😇

2023-10-11 01:18 UTC, abovocado commented on gridy/Sources/Presentations/PlanBoard/TimelineLayout/TimeAxisArea/TimeAxisAreaView.swift
>      @State private var holidays: [Date] = []
완료😇

2023-10-11 01:21 UTC, abovocado commented on gridy/Sources/Presentations/PlanBoard/TimelineLayout/TimeAxisArea/ObservableScrollView.swift
> +//        .coordinateSpace(name: scrollSpace)
이 코드가 포함된 파일의 view가 지금 사용되지 않아서 .swift 파일을 삭제했어요!

2023-10-11 01:35 UTC, abovocado commented on gridy/Sources/Presentations/PlanBoard/TimelineLayout/RightToolBarArea/ScrollDatePickerView.swift
> +            })
완료 🥳

2023-10-11 07:14 UTC, dayo2n commented
귯걸

2023-10-11 07:15 UTC, dayo2n approved these changes

2023-10-11 07:15 UTC, merged