[feat][#12] 프로젝트에 대한 crud api 작업
DeveloperAcademy-POSTECH/MacC-Team15-Ampersand pull request #29
Opened 2023-10-10 18:59 UTC by dayo2n

# Description
close #12
프로젝트를 생성하고 조회하고 수정하고 삭제하는 기능을 개발했습니다

# Screenshots & Demo
![ezgif com-video-to-gif (3)](https://github.com/DeveloperAcademy-POSTECH/MacC-Team15-Ampersand/assets/57654681/e1f157b0-f1e7-46a9-a00c-a8da1472976e)

# To Reviewers 🤲
- 충돌이 상당할 것 같습니다 머지하면서 문제있으면 알려주세요
- @abovocado 릴라이는 여기서 추가된 코드를 보고 프로젝트 보드 하이파이 구현하면서 api 연결작업까지 참고하시면 됩니닷
- 전반적인 프로젝트 모양새는 아래 그림과 같습니다.
  - ContentView에 막 적어뒀던 코드를 모두 삭제하고 AuthenticationView로 분리하였습니다.
  - 기존 AuthenticationView에 있던 SignInWithApple 버튼 코드는 식별하기 쉽도록 SignInWithAppleButtonView를 따로 두었습니다.
![매크로-4 2](https://github.com/DeveloperAcademy-POSTECH/MacC-Team15-Ampersand/assets/57654681/4fe6f476-1e6a-4c10-a50a-a03e058b43af)

2023-10-11 11:02 UTC, abovocado requested changes
제나의 노고에 무한한 감사와 박수를 보냅니다 👏🏻

사실 코드 규칙이 어긋났다거나 한 것은 하나밖에 발견하지 못 했는데요,

로그인 하고 프로젝트 보드로 이동할 때 BackgroundView가 다음과 같이 휘리릭 하는 애니메이션과 함께 보여집니다..

프로젝트 보드의 Hi-Fi가 적용되면 신경쓰지 않아도 될 문제이기 때문에 넘어가도 될까요? 

이 문제만 해결되면 머지해도 될 것 같아요~!

https://github.com/DeveloperAcademy-POSTECH/MacC-Team15-Ampersand/assets/102544840/bd84dca0-bd46-4a7d-87bb-df443d6b6a23

2023-10-12 02:08 UTC, xnoag commented on gridy/Sources/Presentations/ProjectBoard/ProjectBoard.swift
create a new project 버튼으로 새로운 프로젝트를 생성할 때, 순서대로 정렬이 안 됩니다 :)

2023-10-12 02:12 UTC, xnoag commented on gridy/Sources/Models/Project.swift
> +    var pid: String
pid 변수명 수정이 필요합니다 :-)

2023-10-12 02:47 UTC, xnoag commented on gridy/Sources/Presentations/Authentication/AuthenticationView.swift
> +                                            .foregroundColor(.gray.opacity(0.1))
<img width="848" alt="스크린샷 2023-10-12 오전 11 45 29" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team15-Ampersand/assets/125735850/71951ac3-a27b-41e4-85e8-9b66d71a8468">

.foregroundColor는 다음 macOS 버전에 deprecate 된대요!
foregroundStyle(.gray.opacity(0.1))로 수정은 제가 다 할까요??

2023-10-12 02:49 UTC, abovocado approved these changes
짱제나! 짱제나! 짱제나!

2023-10-12 03:32 UTC, dayo2n commented on gridy/Sources/Presentations/Authentication/AuthenticationView.swift
> +                                            .foregroundColor(.gray.opacity(0.1))
수정완료했습니다

2023-10-12 06:21 UTC, xnoag approved these changes
Eres el mejor.
你是最棒的.
あなたが最高です.
Vous êtes le meilleur.
คุณยอดเยี่ยมที่สุดค่ะ.
당신은 최고입니다.

2023-10-12 06:21 UTC, merged