[feat][#40] 상단 메뉴 바 기능 추가해서 단축키 사용가능하게
DeveloperAcademy-POSTECH/MacC-Team15-Ampersand pull request #41
Opened 2023-10-20 13:48 UTC by Jin-s-work

# Description
close #40 
[상단 메뉴 바 기능 추가해서 단축키 사용가능하게 했습니다.

# Screenshots & Demo

# To Reviewers 🤲
- [ ] @dayo2n 의 LoginView.swift 파일에 충돌이 예상됩니다. 확인 부탁드려요.

2023-10-23 04:55 UTC, dayo2n requested changes
로이스 내용도 신경써서 작성해 주세요 ~~~ 
다른 팀원들의 PR을 보면 스크린샷이 포함될 수 있는 경우는 gif도 넣고 무슨 작업을 했는지 간단하든 자세하게든 작성해주고 있답니다!
고생했어요 로이시~~

2023-10-23 04:55 UTC, dayo2n commented on gridy/Sources/gridyApp.swift
> +                //                    .environmentObject(viewModel)
사용하지 않는 주석은 삭제합니다~

2023-10-23 04:55 UTC, dayo2n commented on gridy/Sources/gridyApp.swift
> +
PR 전에 확인해야 할 것 중 하나는 lint warning이에요.. TODO 워닝이나 당장 해결할 수 없는 경우를 제외하고는 모두 수정해 주세요

2023-10-29 04:25 UTC, xnoag commented on gridy/Sources/Presentations/Common/MenuBar.swift
> +                .keyboardShortcut("+", modifiers: [/*@START_MENU_TOKEN@*/.command/*@END_MENU_TOKEN@*/, .shift])
`/*@START_MENU_TOKEN@*/` 이 부분은 주석 처리된 부분일까요-?
특정 기능을 하는 코드일까요-?

2023-10-29 04:31 UTC, xnoag requested changes
<img width="739" alt="스크린샷 2023-10-29 오후 1 27 36" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team15-Ampersand/assets/125735850/18bc0ce6-72ba-426b-9ce0-490aa981b58b">

이 부분 충돌은 PBX 파일에서 일어났네요! develop 브랜치를 풀 받고, 충돌 해결 후에 다시 푸시 해주시면 감사하겠습니다. develop 풀 받는 명령어는 `git pull origin develop --no-rebase` 입니다!


<img width="482" alt="스크린샷 2023-10-29 오후 1 27 52" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team15-Ampersand/assets/125735850/6f928e4d-58a7-4fbf-9ed0-5ff93c7727dc">

아마도 이 부분은 Store가 남아있어야 하는 것으로 보입니다!


리뷰 수정 반영해서 커밋 날려주세용 :)

2023-10-29 05:36 UTC, Jin-s-work commented on gridy/Sources/Presentations/Common/MenuBar.swift
> +                .keyboardShortcut("+", modifiers: [/*@START_MENU_TOKEN@*/.command/*@END_MENU_TOKEN@*/, .shift])
원래 안적혀있던 부분인데 왜 들어갔는지 모르겠네요 수정하겠습니다!

2023-10-29 07:03 UTC, dayo2n commented
이후 변경사항이 너무 많아서 로이스가 수정한 코드를 현 데브 브랜치를 새로 따와서 옮겨붙이는게 나을 것 같은데 어떤가요 ~

2023-10-30 03:42 UTC, Jin-s-work commented
어제 기준 데브 브랜치로 다시 받아와서 작업 하고 있었습니다
일단 지금 중요한 것은 아니라고 생각되어서 다른 기능 먼저 하려하는데 Close 하는게 좋겠지요?

2023-11-02 03:57 UTC, closed without merging