43 feat linearea에 store를 연결하여 plan구조체를 생성합니다
DeveloperAcademy-POSTECH/MacC-Team15-Ampersand pull request #45
Opened 2023-10-23 16:08 UTC by dayo2n

# Description
close #43 
헨리의 mvvm 구조를 TCA로 변경했습니다
내일 쇼케이스가 끝난 후 뷰에 남은 로직들을 TCA로 옮기도록 하겠습니다
child view마다 store를 두고 싶습니다만 보류하겠습니다
일단 한 번 머지해야될 것 같아서 코드가 엉망이에여 TT

# Screenshots & Demo

# To Reviewers 🤲
- [ ] LineAreaView에서 ```
viewStore.send(.createPlan(
                                    // TODO: - Need arguments #1, #2
                                    layer: 1,
                                    row: 2,
                                    target: Plan(
                                        id: "",
                                        periods: [:]),
                                    startDate: startDate,
                                    endDate: endDate
                                ))
```
createPlan의 인자를 이렇게 주고 있는데, 날짜는 선택된 날짜로 들어갈거고 layer랑 row가 각각 1, 2로 고정되어 있어요.
뷰에서 값 받아와서 넣어줄 수 있으면 넣어주면 됩니다
플랜이 생성되는건 테스트해보면서 파이어베이스에서 직접 확인해볼 수 있습니닷

- [ ] 가온의 플젝보드에서 화면 전환할 때 store가 아닌 tag를 쓰고 있어서 급하게 수정하느라 놓친 부분이 있습니다: create 직후 네비게이션. 이슈파서 따로 수정합니다.

2023-10-25 11:12 UTC, xnoag commented on gridy/Sources/Presentations/PlanBoard/PlanBoard.swift
> +//         var verticalMagnification = CGFloat(1.0)
불필요한 주석 ? 삭제 : 그냥두기

2023-10-25 11:13 UTC, xnoag commented on gridy/Sources/Presentations/PlanBoard/PlanBoard.swift
> +//         var verticalMagnification = CGFloat(1.0)
불필요한 주석 ? 삭제 : 그냥두기

2023-10-25 11:18 UTC, xnoag commented on gridy/Sources/Presentations/PlanBoard/TimelineLayout/LineArea/LineAreaView.swift
> +                        }) {
마지막 Button만 줄바꿈이 한 줄 되어있네요 :-)
의도한 것 ? 그냥두기 : 77번 줄 삭제

2023-10-25 11:22 UTC, xnoag commented on gridy/Sources/Presentations/PlanBoard/TimelineLayout/ListArea/ListAreaView.swift
> +
클로저에서 "index"라는 놈이 사용되지 않는 걸로 보입니다.

`
  ForEach(0..<largeTaskTexts.count, id: \.self) { _ in
                            LargeTaskElementView(
                                isLeftButtonClicked: $isLeftButtonClicked,
                                isRightButtonClicked: $isRightButtonClicked,
                                largeTaskElementTextField: $largeTaskTexts[index]
                            )
                            .frame(height: viewStore.lineAreaGridHeight)
`
으로 수정하는 건 어떠신가요?

2023-10-25 11:25 UTC, xnoag commented on gridy/Sources/Presentations/PlanBoard/TimelineLayout/RightToolBarArea/RightToolBarAreaView.swift
> +//                                    viewStore.verticalMagnification = 1.0
불필요한 주석 ? 삭제 : 그냥두기

2023-10-25 11:26 UTC, xnoag commented on gridy/Sources/Presentations/PlanBoard/TimelineLayout/RightToolBarArea/RightToolBarAreaView.swift
> +                        }
action이 비어있습니다.

`// TODO: -`로 해야할 일을 기재해놓으면 나중에 까먹지 않을 것 같네요 :-(

2023-10-25 11:28 UTC, xnoag commented on gridy/Sources/Presentations/PlanBoard/TimelineLayout/ScheduleArea/ScheduleAreaView.swift
> +                        }
onChanged 내부 액션이 비어있습니다.
`// TODO: -`로 할 일을 기재 부탁드립니다.

2023-10-25 11:32 UTC, xnoag commented on gridy/Sources/Presentations/ProjectBoard/ProjectBoardSideView.swift
>                                  .frame(width: proxy.size.width, height: 32)
95번 줄이 공백입니다.

2023-10-25 11:33 UTC, xnoag requested changes
제나 쫌 많이 치시네요.
시뮬레이터 실행 잘 됩니다.
정말 사소한 부분에 대해 코드리뷰를 남겼습니다. 넓은 아량으로 수정해주시면 감사하겠습니다.

2023-10-25 12:33 UTC, dayo2n commented on gridy/Sources/Presentations/PlanBoard/PlanBoard.swift
> +//         var verticalMagnification = CGFloat(1.0)
ㅋㅋ 삼항연산 좀 치시네요 ㅋㅋ 필요한건데 헨리가 추후 처리한다고 해서 얘기하고 주석처리해두었습니다 ~

2023-10-25 12:34 UTC, dayo2n commented on gridy/Sources/Presentations/PlanBoard/TimelineLayout/LineArea/LineAreaView.swift
> +                        }) {
이것은 사실 제 코드가 아니랍니다... 안그래도 버튼을 싹 클로저로만 표시하고 싶었는데 내친김에 다 처리하겠읍니다

2023-10-25 13:01 UTC, dayo2n commented on gridy/Sources/Presentations/PlanBoard/TimelineLayout/RightToolBarArea/RightToolBarAreaView.swift
> +//                                    viewStore.verticalMagnification = 1.0
PlanBoard.swift의 주석과 동일한 내용! 현재는 아무 동작도 안하고 있어서 주석처리 해두었습!니다 그냥둡니다!

2023-10-25 13:08 UTC, dayo2n commented on gridy/Sources/Presentations/PlanBoard/TimelineLayout/ScheduleArea/ScheduleAreaView.swift
> +                        }
와우 가온 잘봤네요
코드가 있는 부분인데 옮기면서 누락되었어요
아래와 같이 수정되었습니다
```
.gesture(
                    MagnificationGesture()
                        .onChanged { value in
                            viewStore.send(.magnificationChangedInScheduleArea(value))
                        }
                )
```

2023-10-25 13:12 UTC, dayo2n commented
> 제나 쫌 많이 치시네요. 시뮬레이터 실행 잘 됩니다. 정말 사소한 부분에 대해 코드리뷰를 남겼습니다. 넓은 아량으로 수정해주시면 감사하겠습니다.

리뷰 감사요 가온~
꼼꼼하게 봐줘서 놓친 코드도 잘 봤습니다
다시 리뷰 요청 드리오니 확인 부탁드립니다 ^.^

2023-10-26 00:22 UTC, abovocado requested changes
당신의 노고에 무한한 감사를.

이거 TCA로 옮기는 것만 해도 굉장한 시간이 필요했을턴디,, 언제 다 했나요?

제나의 시간은 천천히 흐른다...

2023-10-26 00:22 UTC, abovocado commented on gridy/Sources/Presentations/PlanBoard/PlanBoard.swift
> +
State부분 인덴트 전체적으로 조정 필요!합니다~! viewModel에 있던게 들어오면서 바뀐것 같아용,,,

2023-10-26 00:22 UTC, abovocado commented on gridy/Sources/Presentations/PlanBoard/TimelineLayout/LineArea/LineAreaView.swift
>      @State private var rowStroke = CGFloat(0.5)
이거 두개는 Store에 있는 듯!

2023-10-26 00:46 UTC, dayo2n commented on gridy/Sources/Presentations/PlanBoard/TimelineLayout/RightToolBarArea/RightToolBarAreaView.swift
> +                        }
빈 게 맞는 것 같습니다! 정렬을 맞추려고 버튼 만들어놓은 것 같아요 ~~
<img width="215" alt="스크린샷 2023-10-26 오전 9 46 48" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team15-Ampersand/assets/57654681/17b2cf33-7495-41ff-8c74-307713563202">

2023-10-26 00:47 UTC, dayo2n commented on gridy/Sources/Presentations/PlanBoard/PlanBoard.swift
> +
헉 맞아요 릴리 TT 고마워요

2023-10-26 00:51 UTC, dayo2n commented on gridy/Sources/Presentations/PlanBoard/TimelineLayout/LineArea/LineAreaView.swift
>      @State private var rowStroke = CGFloat(0.5)
수정완 ~~~

2023-10-26 00:53 UTC, xnoag approved these changes
짱제나
짱최고
짱구닮음

2023-10-26 01:51 UTC, dayo2n commented
> 당신의 노고에 무한한 감사를.
> 
> 이거 TCA로 옮기는 것만 해도 굉장한 시간이 필요했을턴디,, 언제 다 했나요?
> 
> 제나의 시간은 천천히 흐른다...

살짝 눈물을 머금으며 옮겨놨읍니다 ^^,,, 장난이고요 열심히 옮겼읍니다
리뷰 고마워요 ㄹ릴리

2023-10-26 01:55 UTC, abovocado approved these changes
리뷰 반영된 것 확인했습니다!

울고 싶을 땐 울어도 돼... 😭

2023-10-26 01:56 UTC, merged