Feature/33 plan crud api
DeveloperAcademy-POSTECH/MacC-Team15-Ampersand pull request #49
Opened 2023-10-27 05:55 UTC by dayo2n

# Description
createPlan, createLayer, createPlanType을 수정했습니다
- 생각해보니 `map`으로 전달해주는게 Plan 타입이 아니라 PlanID를 담은 string이더라고요. 그래서 모든 플랜을 Plan 타입으로 반환해주는 fetchAllPlans라는 함수를 PlanBoard에 생성하였습니다. PlanBoard의 `existingAllPlans["plan 아이디"]`로 접근 가능합니다.  APIService에서는 readAllPlans로 불립니다.
  접근하는 깊이가 깊어진다는게 매우 거슬립니다 ... 하지만 일단 가장 빠르게 처리할 수 있는 방법으로 수정해뒀어요 조만간 처리할게요
- 릴리에게 설명해주었는데 createPlan 함수가 조금 바뀌었습니다. lane의 높이는 맞춰줄 수 없는 상태라 레인들 중간에 빈 아이템을 두고 생성하더라도 위쪽 정렬될 것으로 예상됩니다. layer는 빈레이어 생성가능
- Firestore에서 Plans, Lanes, PlanTypes, Projects로 컬렉션을 각각 나누었는데 생각해보니 Plans, Lanes, PlanTypes는 각각 해당하는 Projects 컬렉션에 종속되어야 할 것 같습니다. 이슈 생성해두겠습니다~~
- 노션 모델구조 / 명세서에 함수 인자나 리턴값을 어떻게 쓰는지 계속 업데이트하고 있습니다. 사용해야할 땐 참고 바랍니다 ~!~

2023-10-27 06:26 UTC, abovocado commented
선댓글 후리뷰 시작.

2023-10-27 11:20 UTC, xnoag commented
선댓글 후리뷰 시작합니다.

2023-10-27 11:34 UTC, xnoag commented on gridy/Sources/Presentations/PlanBoard/PlanBoard.swift
> +                    newPlan = Plan(id: "", // APIService에서 자동 생성
// 주석이 있긴한데, 급한 건 아니니 다른 거 수정할 때 같이 한 번 부탁드려요~!

2023-10-27 11:34 UTC, xnoag commented on gridy/Sources/Presentations/PlanBoard/PlanBoard.swift
> +                    newPlan = Plan(id: "", // APIService에서 자동 생성
// 주석이 있긴한데, 급한 건 아니니 다른 거 수정할 때 같이 한 번 부탁드려요~!

2023-10-27 11:36 UTC, xnoag commented on gridy/Sources/Presentations/PlanBoard/TimelineLayout/LineArea/LineAreaView.swift
> +                                        parentLaneID: "CbOueYeOwslUsDDQnkEV",
parentLandID는 Cb0...로 고정되는 건가요? Firebase와 관련된 건가요??..?

2023-10-27 11:38 UTC, xnoag requested changes
잘 동작하는 거 확인했습니다.
코드 리뷰이기 민망할 정도라,,, 간단한 확인과 질문 남겼습니다!
감사합니다 제나

2023-10-27 12:00 UTC, abovocado approved these changes
필요한 API서비스의 코드를 이해하느라고 리뷰가 늦었습니다...

제니가 주석에 남겨준 TODO 는 (PlanBoard의 fetch부분) 제가 반영해서 수정하도록 하겠습니다!

지금은 대전에 있을 제니를 추억하며...🥳 (PR 제목에서 수정해야 하는 부분을 찾아보시오~)

Ps. listArea에 CreatePlan 붙이면서 혹시나 에러가 발생하는 Flow는 없는지 확인도 해볼게요!

@xnoag @dayo2n 주석을 수정하고 다시 push하는게 번거롭다면 바로 다음PR인 저의 PR에 어차피 merge 후 push를 한번 해야 해서 제가 수정해도 괜찮습니다~

2023-10-27 12:30 UTC, xnoag commented
> 필요한 API서비스의 코드를 이해하느라고 리뷰가 늦었습니다...
> 
> 제니가 주석에 남겨준 TODO 는 (PlanBoard의 fetch부분) 제가 반영해서 수정하도록 하겠습니다!
> 
> 지금은 대전에 있을 제니를 추억하며...🥳 (PR 제목에서 수정해야 하는 부분을 찾아보시오~)
> 
> Ps. listArea에 CreatePlan 붙이면서 혹시나 에러가 발생하는 Flow는 없는지 확인도 해볼게요!
> 
> @xnoag @dayo2n 주석을 수정하고 다시 push하는게 번거롭다면 바로 다음PR인 저의 PR에 어차피 merge 후 push를 한번 해야 해서 제가 수정해도 괜찮습니다~

PR 제목에서 수정해야 하는 부분을 찾아보시오~ -> 원숭이도 나무에서 떨어졌군요

2023-10-28 01:57 UTC, dayo2n commented on gridy/Sources/Presentations/PlanBoard/TimelineLayout/LineArea/LineAreaView.swift
> +                                        parentLaneID: "CbOueYeOwslUsDDQnkEV",
아 이것도 릴리에게만 설명했는데 뷰에서 parentLaneID를 전달할 수 있어야해서 담아놨고 앞으로 수정될 부분입니다 ~ TODO로 달아둘게요!

2023-10-28 02:14 UTC, dayo2n commented
@xnoag @abovocado  여러분의 소중한 코드리뷰 고맙습니다
수정해야 될 것들이 주석처리만 하면 돼서 모두 반영해두었습니다
제목도 변경했습니다 :))
가온은 확인 후에 승인 부탁합니다 ~

2023-10-28 05:59 UTC, xnoag approved these changes
짱제나! 짱제나!

2023-10-28 06:00 UTC, merged