[feat][#32] listArea 구현
DeveloperAcademy-POSTECH/MacC-Team15-Ampersand pull request #50
Opened 2023-10-27 09:53 UTC by abovocado

# Description
close [#32 ]
listArea 스켈레톤을 완료했습니다. 
로이스가 코드를 사용할 수 있도록 머지합니다. 또한 제나의 PR 머지 후 createPlan을 붙이기 위해서 머지합니다!
그말인 즉슨 이 머지가 끝나면 listArea에서 createPlan 코드와 focusState만 붙일 것 같아요. 그러면 일단 listArea는 끝!

- listArea Grid 및 보여주는 column 개수에 따라 Grid 변경
- layer 추가 및 layer 번호 우클릭 시 추가 가능 버튼 POP-UP
- map 정보 받아와서 layer 엎기
- listItemView, listItemEmptyView 생성 

> 기존에 width에 따라 나뉘어져있던 3개의 TaskElementView들을 하나로 합쳤습니다. 
> map의 구조체 정보를 받아와서 보여주고 수정이 일어나는게 listItemView
> 빈 dummy의 정보를 보여주고 plan create이 일어나는게 listItemEmptyView입니다.
> width는 보여주는 layer개수에 따라 조정됩니다.

- listItemView Hover, click, double click flow 구현

# Screenshots & Demo

https://github.com/DeveloperAcademy-POSTECH/MacC-Team15-Ampersand/assets/102544840/8ca4e951-eacf-49f9-8928-1ee1a9b3b6c4

# To Reviewers 🤲
- [ ] @Jin-s-work 로이스가 listAreaView에서 작업해야 해서 일단 머지 합니다.
- [ ] @xnoag 가온과 함께 더블클릭이랑 클릭 동시 사용시 발생하는 지연 문제를 고민해야 합니다.

2023-10-27 09:54 UTC, abovocado commented
일단 리뷰하지 말아주세용 ㅜㅜ 제나걸 머지하는걸 깜빡했읍니다 ㅜㅜ

2023-10-28 07:17 UTC, abovocado commented on gridy/Sources/Presentations/PlanBoard/PlanBoard.swift
> +        var showingRows = 20
헐 이부분 지금 안쓰네 삭제할게요

2023-10-28 07:34 UTC, xnoag commented on gridy/Sources/Presentations/PlanBoard/PlanBoard.swift
> +        // TODO: listAreaOnAppear delete
커멘트를 달아도 될정도인지 모르겠지만, `TODO: -`로 부탁드려요~!

2023-10-28 07:46 UTC, xnoag commented on gridy/Sources/Presentations/PlanBoard/TimelineLayout/ListArea/ListAreaView.swift
> +//  Created by SY AN on 10/20/23.
?

2023-10-28 07:54 UTC, dayo2n requested changes
ListItemView과 ListItemEmptyView는 각각 따로 정의되어야 하는거겠죠 ?~?

2023-10-28 07:54 UTC, dayo2n commented on gridy/Sources/Presentations/Authentication/Authentication.swift
> +                // TODO: - navigation 로직 수정필요 @제나
넵 🫡

2023-10-28 07:54 UTC, dayo2n commented on gridy/Sources/Presentations/PlanBoard/PlanBoard.swift
> +        var listColumnWidth: [[CGFloat]] = [[266.0], [132.0, 132.0], [24.0, 119.0, 119.0]]
showingLayers는 타입 추론이 가능한 경우네요 ~!
listColumnWidth는 아마도 Double형으로 추론할듯한데  CGFloat(266.0)으로 감싸주면 CGFloat이라는 타입을 명시해줄 수 있지만 타입을 명시하는 것이 더 깔끔하니 그냥 두어도 될 것 같습니다 ~!

2023-10-28 07:54 UTC, dayo2n commented on gridy/Sources/Presentations/PlanBoard/TimelineLayout/ListArea/ListAreaView.swift
> +                                    .frame(width: viewStore.listColumnWidth[viewStore.showingLayers.count-1][forIndex], height: viewStore.lineAreaGridHeight / 2)
여기 코드가 한줄에 안들어와서 개행하면 좋겠습니다~
```suggestion
                                    .frame(
                                    width: viewStore.listColumnWidth[viewStore.showingLayers.count-1][forIndex], 
                                    height: viewStore.lineAreaGridHeight / 2
                                    )
```

2023-10-28 07:54 UTC, dayo2n commented on gridy/Sources/Presentations/PlanBoard/TimelineLayout/TimelineLayoutViewModel.swift
이 파일은 삭제되어야 합니다! 삭제되어도 정상 동작해야 합니다~~

2023-10-28 07:56 UTC, xnoag commented on gridy/Sources/Presentations/PlanBoard/TimelineLayout/TimelineLayoutViewModel.swift
Pull 받은 Xcode에서는 `TimelineLayoutViewModel.swift` 가 없습니다.
릴리에게 구두로 전달하였습니다.

2023-10-28 07:57 UTC, dayo2n commented on gridy/Sources/Presentations/PlanBoard/TimelineLayout/TimelineLayoutViewModel.swift
넹 finder에서 직접 삭제해야 할 거에요~~

2023-10-28 07:58 UTC, xnoag commented on gridy/Sources/Presentations/PlanBoard/TimelineLayout/ListArea/ListItemView.swift
> +            // TODO: unitHeight * 내가 가진 lane 개수
`TODO: -`

구두로는 상냥하게 전달했습니다.

2023-10-28 07:59 UTC, xnoag requested changes
한 게 없어보이지만, 릴리와 함께 있는 관계로 구두로 열심히 리뷰하였습니다.
릴리 최고~!!
앞으로는 도둑질 하지 말아주세요 :-(

2023-10-28 08:24 UTC, abovocado commented on gridy/Sources/Presentations/PlanBoard/TimelineLayout/ListArea/ListAreaView.swift
> +//  Created by SY AN on 10/20/23.
이 대화는 닫도록 할게요.

2023-10-28 08:24 UTC, abovocado commented on gridy/Sources/Presentations/PlanBoard/TimelineLayout/TimelineLayoutViewModel.swift
삭제 완료!

2023-10-28 08:24 UTC, abovocado commented on gridy/Sources/Presentations/PlanBoard/TimelineLayout/TimelineLayoutViewModel.swift
삭제 완료~! 삭제 후 구동되는 것도 확인!

2023-10-28 08:24 UTC, abovocado commented on gridy/Sources/Presentations/Authentication/Authentication.swift
> +                // TODO: - navigation 로직 수정필요 @제나
아마 이거 같이 있을 때 적었던 코드로 기억합니다~! @dayo2n 후후

2023-10-28 08:24 UTC, abovocado commented on gridy/Sources/Presentations/PlanBoard/PlanBoard.swift
> +        // TODO: listAreaOnAppear delete
확인! 확인하면서 헨리 TODO도 수정해두었어요.

2023-10-28 08:24 UTC, abovocado commented on gridy/Sources/Presentations/PlanBoard/TimelineLayout/ListArea/ListItemView.swift
> +            // TODO: unitHeight * 내가 가진 lane 개수
해당 파일 TODO 모두 완료!

2023-10-28 08:24 UTC, abovocado commented on gridy/Sources/Presentations/PlanBoard/PlanBoard.swift
> +        var listColumnWidth: [[CGFloat]] = [[266.0], [132.0, 132.0], [24.0, 119.0, 119.0]]
아하.. 이 부분을 계속해서 놓치는군요...
showingLayers는 삭제 했습니다!

2023-10-28 08:24 UTC, abovocado commented on gridy/Sources/Presentations/PlanBoard/TimelineLayout/ListArea/ListAreaView.swift
> +                                    .frame(width: viewStore.listColumnWidth[viewStore.showingLayers.count-1][forIndex], height: viewStore.lineAreaGridHeight / 2)
개행 완료~!

2023-10-28 08:45 UTC, xnoag approved these changes
승인합니다.

2023-10-28 13:23 UTC, dayo2n approved these changes
수고했어요 릴리~~ 짱~~~~ 🤍

2023-10-28 13:23 UTC, merged