[feat][#57] 캘린더뷰 제작 완료, 일부 월에서 뷰 크기 변하는 문제 추후 해결
DeveloperAcademy-POSTECH/MacC-Team15-Ampersand pull request #58
Opened 2023-11-02 16:54 UTC by Jin-s-work

# Description
close [#57]
캘린더뷰 제작 완료, 일부 월에서 뷰 크기 변하는 문제 추후 해결

# Screenshots & Demo
https://github.com/DeveloperAcademy-POSTECH/MacC-Team15-Ampersand/assets/61958748/aaac4af3-d097-4f64-bf28-8a45e1de65cf

# To Reviewers 🤲
- [ ] 일부 월에서 뷰 크기가 변하는 문제는 추후 해결 예정

2023-11-03 10:08 UTC, xnoag commented on gridy/Sources/Presentations/PlanBoard/CalendarLayout/CalendarLayoutTemp.swift
> +                let days: [String] = ["일", "월", "화", "수", "목", "금", "토"]
`var body: some View {`
바로 아랫줄에 배치하는 게 가독성이 좋을 것 같아요 로이스~

2023-11-03 10:09 UTC, xnoag commented on gridy/Sources/Presentations/PlanBoard/CalendarLayout/CalendarLayoutTemp.swift
> +                let columns = Array(repeating: GridItem(.fixed(22)), count: 7)
`var body: some View {`
바로 아랫줄에 배치하는 게 가독성이 좋을 것 같아요 로이스~

2023-11-03 10:15 UTC, xnoag commented on gridy/Sources/Presentations/PlanBoard/CalendarLayout/CalendarLayoutTemp.swift
> +            VStack(alignment: .center) {
VStack에 `spacing: 8` 추가 부탁해용

2023-11-03 10:20 UTC, xnoag commented on gridy/Sources/Presentations/PlanBoard/CalendarLayout/CalendarLayoutTemp.swift
> +                    }
ForEach에 cardView만 있으면 ZStack을 안 써도 될 것 같아요!

2023-11-03 10:21 UTC, xnoag commented on gridy/Sources/Presentations/PlanBoard/CalendarLayout/CalendarLayoutTemp.swift
> +                let isSunday = value.date.dayOfSunday() == 1  // 1은 일요일을 나타냅니다.
설명이 필요한 주석은 `///` 로 표기하기로 했어요 로이스~

2023-11-03 10:22 UTC, xnoag commented on gridy/Sources/Presentations/PlanBoard/CalendarLayout/CalendarLayoutTemp.swift
> +                        .foregroundColor(Color.subtitle)
foregroundColor는 곧 Deprecated된다고 해서, foregroundStyle로 통일 해주세요~!

2023-11-03 10:24 UTC, xnoag requested changes
로이스 고생했어요!
주석이랑 foregroundColor 커멘트는 한 번만 달아놨는데, 다른 것들도 수정해서 반영해주세용!

2023-11-03 10:29 UTC, Jin-s-work commented on gridy/Sources/Presentations/PlanBoard/CalendarLayout/CalendarLayoutTemp.swift
> +            VStack(alignment: .center) {
이거는 헨리가 간격맞춘다고 이렇게 한거라서 이렇게 냅둘게요!

2023-11-03 10:30 UTC, Jin-s-work commented on gridy/Sources/Presentations/PlanBoard/CalendarLayout/CalendarLayoutTemp.swift
> +                        .foregroundColor(Color.subtitle)
리뷰 고마어요 가온! 고치도록 할게요~

2023-11-03 10:31 UTC, Jin-s-work commented
리뷰 고마어요 가온! 고치도록 할게요 :)

2023-11-03 18:45 UTC, dayo2n requested changes

2023-11-03 18:52 UTC, dayo2n requested changes

2023-11-03 18:52 UTC, dayo2n commented on gridy.xcodeproj/project.pbxproj
> +		D167A0462AF40B0600B70E5E /* CalendarView.swift */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; name = CalendarView.swift; path = ../../../../../../../Documents/CalendarView.swif
아마도 헨리가 준 파일을 로컬에서 그대로 가져다가 붙인 것 같은데,
이렇게 하면 프로젝트 빌드 파일에서 로이스의 로컬 경로를 읽게 되어서 파일 정보를 찾을 수가 없어요
다른 사람들은 빌드가 안될겁니다

다른 사람의 코드가 필요하면 일단 프로젝트에서 파일을 생성하고 복붙하거나,
로컬에서 이 프로젝트 파일이 있는 곳에 원본파일을 먼저 옮기고, 해당 위치에서 다시 프로젝트로 끌어넣어야 합니다

이번에는 제가 수정해서 올리겠습니다

2023-11-03 19:14 UTC, dayo2n requested changes
그리고 Color 에셋에 대한 정의가 하나도 안들어와 있어서 실행이 안됩니다
에셋이 정의되어 있는 헨리가 올린 피알과 같은 브랜치에서 작업했다면 왜 별개의 피알로 올라와있는지 궁금합니다
이 피알을 올리기 전에 프로젝트를 실행해 보았는지도 궁금하네요 분명 실행이 되지 않았을텐데 !!

2023-11-04 05:30 UTC, Jin-s-work commented on gridy.xcodeproj/project.pbxproj
> +		D167A0462AF40B0600B70E5E /* CalendarView.swift */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; name = CalendarView.swift; path = ../../../../../../../Documents/CalendarView.swif
해결해줘서 고마워요 제나!

2023-11-04 05:33 UTC, Jin-s-work commented
새로 브랜치를 파서 해달라는 부탁 받아서 했어요!
PR 받을때 리뷰하는 사람도 실행해서 확인해보아야 했을텐데 고려하지 못해서 죄송해요
다음 PR 부터는 주의하도록 하겠습니다

2023-11-04 11:55 UTC, dayo2n approved these changes
수고하셨어요 로이스 ~~
리뷰 반영 너무 잘되었고 ContentView만 원래대로 수정하고 머지해 주세요!
이 부분은 잘 반영하리라 믿고 미리 승인을 남깁니다 화이팅 ദ്ദി*ˊᗜˋ*)

2023-11-04 11:55 UTC, dayo2n commented on gridy/Sources/ContentView.swift
> +            CalendarView()
여기 코드 롤백해주세요 ~

2023-11-04 11:57 UTC, dayo2n commented
pbxproj파일에서 오류나는 부분은 해결하기 쉬운 부분이라 충돌해결하고 머지 바랍니다!!
잘 모르겠다면 도움을 요청해 주십시옹

2023-11-05 12:39 UTC, Jin-s-work commented
> pbxproj파일에서 오류나는 부분은 해결하기 쉬운 부분이라 충돌해결하고 머지 바랍니다!! 잘 모르겠다면 도움을 요청해 주십시옹

다른 부분은 다 해결했는데 pbxproj 파일에서 에러가 나는 부분은 어떻게 확인 할 수 있을까요? visual studio로 열어서 pbxproj 파일 확인했는데 제나가 바로 전에 해결한 부분이랑 똑같은거 같아서요

2023-11-06 00:23 UTC, xnoag approved these changes
수고하셨습니다. 로이스

<img width="969" alt="스크린샷 2023-11-06 오전 9 22 45" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team15-Ampersand/assets/125735850/ee2efdc0-f5be-4f6a-b831-8d8ce430e8e3">

코드리뷰 반영하고, 된 부분은 `Resolve conversation` 눌러주시면 더 좋을 것 같아요~

2023-11-06 02:52 UTC, merged