Feature/55 view 구조 제작
DeveloperAcademy-POSTECH/MacC-Team15-Ampersand pull request #59
Opened 2023-11-03 16:33 UTC by OreobrO

# Description
close #[55]
- MVP모델에 맞는 뷰 구조로 변경을 위해 파일 생성 및 삭제 진행하였습니다.
- 기존 파일로 별도 구분했던 child View들을 View의 Extension으로 관리하여 코드를 간소화 하였습니다.
- SystemColor가 Assets에 반영되었습니다.
- ProjectBoardView의 뷰 코드가 완성되었습니다. SystemColor까지 반영 완료.

# Screenshots & Demo
<img width="319" alt="스크린샷 2023-11-04 오전 1 30 55" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team15-Ampersand/assets/120009346/0bf75854-ec4d-418c-8be8-404e62c635cd">

# To Reviewers 🤲
- [ ] 기존 AuthentificationView에 문제가 발생한 듯 합니다. 해당 코드는 주석처리한 상태입니다.
- [ ] 기존에 있던 뷰를 새로운 뷰로 기능 이식하는 작업은 추후 진행 바랍니다.

2023-11-03 18:06 UTC, abovocado requested changes
엄청난,,, 파일 수정이군뇨...

우선 돌아가는걸 보게 되어서 정말 영광입니다 이 브랜치에 참여하신 모든 여러분들의 노고에, 그리고 피 땀 눈물에 무한한 박수를 보냅니다.

전체적으로 린트에 맞는 수정과 삭제되어야할 코드들이 있습니다! 

확인하시어 Push 올려주시면 또 구경하러 올게요~ 🥳

2023-11-03 18:06 UTC, abovocado commented on gridy/Sources/Presentations/ProjectBoard/ProjectItemView.swift
> +//struct ProjectItemView: View {
사용되지 않을 코드라면 삭제를 부탁드려요~

2023-11-03 18:17 UTC, dayo2n commented on gridy/Sources/Presentations/Common/TabBarView.swift
> +extension TabBarView {
개행없는 것 맞나요 ?
별개의 function이나 struct, enumeration을 작성할 때도 개행하고 있습니다
스타일 수정 바랍니다 ~~

2023-11-03 18:26 UTC, dayo2n commented on gridy/Sources/Presentations/PlanBoard/PlanBoard.swift
이 부분은 오픈소스에 기여할 때도 필수적인 부분인데, 기존코드에서 불필요한 수정은 진행하지 않습니다.
PlanBoard에서 수정은 개행 삭제밖에 없어서 코드 스타일을 맞추려고 삭제한 줄 알았는데 다른 파일을 보니 맞춰진 것도 아니네요.
이 부분을 @xnoag 이 질문했던듯한데 가온의 수정인가요?!
코드컨벤션 통일이 필요하다면 한 번 언급하고 얼라인해주시길 바랍니다 ~~

2023-11-03 18:26 UTC, dayo2n commented on gridy/Sources/Presentations/PlanBoard/TimelineLayoutView.swift
> +
개행 삭제

2023-11-03 18:28 UTC, dayo2n commented on gridy/Sources/Presentations/ProjectBoard/ProjectBoardView.swift
> +        @State var planBoardItemHover: Bool = false
타입 추론 가능

2023-11-03 18:29 UTC, dayo2n commented on gridy/Sources/Presentations/ProjectBoard/ProjectBoardView.swift
> +                .shadow(color: planBoardItemHover ? .black.opacity(0.25) : .clear, radius: 4, y: 4)
여기는 파라미터마다 개행해 주세요

2023-11-03 18:33 UTC, dayo2n commented on gridy/Sources/Presentations/Common/SplashView.swift
> +//  Created by xnoag on 11/1/23.
@xnoag 가온. 옥상으로 따라오세요.

2023-11-04 01:32 UTC, OreobrO commented on gridy/Sources/Deprecated/TimelineLayoutViewDeprecated.swift
> +////  TimelineLayoutView.swift
네! 기존에 사용했던 코드 새로운 코드에 이식하기 위해서 남겨놓았습니다! Deprecated폴더 안에, 삭제예정인 파일들

2023-11-04 01:32 UTC, OreobrO commented on gridy/Sources/Deprecated/ProjectBoardViewDeprecated.swift
> +////  ProjectBoardView.swift
네! 기존에 사용했던 코드 새로운 코드에 이식하기 위해서 남겨놓았습니다! Deprecated폴더 안에, 삭제예정인 파일들

2023-11-04 01:32 UTC, OreobrO commented on gridy/Sources/ContentView.swift
> +//            AuthenticationView()
넵!

2023-11-04 01:37 UTC, OreobrO commented on gridy/Sources/Presentations/Common/TabBarView.swift
> +extension TabBarView {
확인했습니다!

2023-11-04 01:37 UTC, OreobrO commented on gridy/Sources/Presentations/ProjectBoard/ProjectBoardSideView.swift
>  import ComposableArchitecture
넵2

2023-11-04 01:38 UTC, OreobrO commented on gridy/Sources/Presentations/ProjectBoard/ProjectBoardView.swift
> +    @State private var isExpanded: Bool = true
확인!

2023-11-04 01:38 UTC, OreobrO commented on gridy/Sources/Presentations/ProjectBoard/ProjectBoardView.swift
> +extension ProjectBoardView {
개행 되는게 좋아보여요!

2023-11-04 01:39 UTC, OreobrO commented on gridy/Sources/Presentations/ProjectBoard/ProjectBoardView.swift
>                          }
넵@

2023-11-04 01:40 UTC, OreobrO commented on gridy/Sources/Presentations/ProjectBoard/ProjectItemView.swift
> +//struct ProjectItemView: View {
이것두 기능 이식하면서 기존 코드 참고예정으로, 빌드할 때 이름 충돌이 나서 주석처리 되어있습니다.

2023-11-04 01:41 UTC, OreobrO commented on gridy/Sources/Presentations/Common/TabBarView.swift
> +                    Image(systemName: "xmark").foregroundStyle(planBoardTabClicked ? Color.title : planBoardTabHover ? Color.textInactive : .clear)
넵!

2023-11-04 01:42 UTC, OreobrO commented on gridy/Sources/Presentations/PlanBoard/RightToolBarView.swift
> +        .frame(width: 600, height: 350)    }
넵!

2023-11-04 01:43 UTC, OreobrO commented on gridy/Sources/Presentations/PlanBoard/TimelineLayoutView.swift
> +            TopToolBarArea(shareImageClicked: $shareImageClicked, boardSettingClicked: $boardSettingClicked, rightToolBarClicked: $rightToolBarClicked).frame(height: 36)
확인이요!

2023-11-04 01:43 UTC, OreobrO commented on gridy/Sources/Presentations/PlanBoard/TimelineLayoutView.swift
> +
넵

2023-11-04 01:44 UTC, OreobrO commented on gridy/Sources/Presentations/Common/TabBarView.swift
> +extension TabBarView {
완료했습니다!

2023-11-04 01:46 UTC, OreobrO commented on gridy/Sources/Presentations/PlanBoard/PlanBoard.swift
확인이요!

2023-11-04 01:48 UTC, OreobrO commented on gridy/Sources/Presentations/ProjectBoard/ProjectBoardView.swift
> +                .shadow(color: planBoardItemHover ? .black.opacity(0.25) : .clear, radius: 4, y: 4)
혹시 3항연산자의 개행을 말하는걸까요?

2023-11-04 01:48 UTC, OreobrO commented on gridy/Sources/Presentations/Common/SplashView.swift
> +//  Created by xnoag on 11/1/23.
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2023-11-04 01:48 UTC, OreobrO commented on gridy/Sources/Presentations/ProjectBoard/ProjectBoardView.swift
> +        @State var planBoardItemHover: Bool = false
완료

2023-11-04 01:48 UTC, OreobrO commented on gridy/Sources/Presentations/PlanBoard/TimelineLayoutView.swift
> +
완료

2023-11-04 01:48 UTC, OreobrO commented on gridy/Sources/Presentations/PlanBoard/TimelineLayoutView.swift
> +//                .frame(width:32, height:167)
넵

2023-11-04 01:56 UTC, OreobrO commented
폴더와 파일구조 개선 과정 중 같은 이름의 새로운 뷰 코드를 작성하게 되면서, 오류가 나지 않기 위해 주석처리된 코드들은 추후 기능 이식하는 시점에 하나씩 삭제될 예정입니다!

2023-11-04 02:12 UTC, dayo2n requested changes
푸시가 하나 덜된건지 .. 반영이 안되어있는 부분들을 다시 확인해 주세요 ~!

2023-11-04 02:12 UTC, dayo2n commented on gridy/Sources/Presentations/PlanBoard/BoardSettingView.swift
> +        .frame(width: 600, height: 350)    }
@OreobrO 여기 수정 안되었어요~!~

2023-11-04 02:12 UTC, dayo2n commented on gridy/Sources/Presentations/PlanBoard/TopToolBarArea.swift
> +
@OreobrO 여기두

2023-11-04 02:12 UTC, dayo2n commented on gridy/Sources/Presentations/ProjectBoard/ProjectBoardView.swift
> +        @State var planBoardItemHover: Bool = false
@OreobrO 여기도 반영안되어있는데 완료 맞나요 ..? 🫠

2023-11-04 02:16 UTC, dayo2n requested changes

2023-11-04 02:16 UTC, dayo2n commented on gridy/Sources/Presentations/PlanBoard/TimelineLayoutView.swift
> +
개행 삭제!

2023-11-04 02:17 UTC, dayo2n commented on gridy/Sources/ContentView.swift
> +//            AuthenticationView()
여기 주석처리 되돌려지지 않았어요 ~

2023-11-04 02:19 UTC, dayo2n commented on gridy/Sources/Presentations/Common/TabBarView.swift
> +struct TabBarView: View {
다음주 이슈에서 해결합시다 ~~

2023-11-04 02:27 UTC, dayo2n requested changes

2023-11-04 02:27 UTC, dayo2n commented on gridy/Sources/Presentations/Common/TabBarView.swift
> +            print("ZZ")
print 로그 삭제

2023-11-04 03:06 UTC, OreobrO commented
[fix][#55] 안쓰는 파일 삭체 및 내용 이전 에정인 코드들은 주석 처리
위 Commit 내용 설명드리겠습니다.

예전 파일 구조에서 딱히 작성되지 않았으며 사용되지 않는 폴더와 코드는 삭제하였습니다.
예전 파일 구조에서 코드를 작성하였으나, 새로운 뷰 구조에 이전되어야하는 코드는 주석처리 하였습니다.

2023-11-04 04:11 UTC, dayo2n approved these changes
이 부분은 수정안되었어요 승인남기니 반드시 수정하고 머지해 주세요
<img width="867" alt="스크린샷 2023-11-04 오후 1 11 02" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team15-Ampersand/assets/57654681/9dd82e79-49a3-41a7-ae7a-566a67e68665">

2023-11-04 04:48 UTC, abovocado commented on gridy/Sources/ContentView.swift
> +//            AuthenticationView()
확인완료

2023-11-04 04:54 UTC, abovocado commented on gridy/Sources/Presentations/PlanBoard/TimelineLayoutView.swift
> +struct TimelineLayoutView: View {
@OreobrO 파일에서 Cmd + a 후 control + I

부탁드립니다~!

2023-11-04 04:57 UTC, abovocado commented on gridy/Sources/Presentations/PlanBoard/RightToolBarView.swift
> +struct RightToolBarView: View {
@OreobrO 혹이 이 뷰 어떻게 되는걸까요~? 코멘트 달아주세욥!

2023-11-04 05:08 UTC, abovocado commented on gridy/Sources/Presentations/ProjectBoard/ProjectBoardView.swift
> +                .shadow(color: planBoardItemHover ? .black.opacity(0.25) : .clear, radius: 4, y: 4)
color:   ,
radius 
인 것 같아용~

2023-11-04 06:28 UTC, OreobrO commented on gridy/Sources/Presentations/ProjectBoard/ProjectBoardView.swift
> +                .shadow(color: planBoardItemHover ? .black.opacity(0.25) : .clear, radius: 4, y: 4)
아 이제 이해했어요

2023-11-04 06:32 UTC, xnoag commented on gridy/Sources/Presentations/ProjectBoard/ProjectBoardView.swift
> +                .shadow(color: planBoardItemHover ? .black.opacity(0.25) : .clear, radius: 4, y: 4)
[fix][#55] 파라미터마다 개행

@dayo2n

2023-11-04 06:34 UTC, xnoag commented on gridy/Sources/Presentations/PlanBoard/TimelineLayoutView.swift
> +struct TimelineLayoutView: View {
[fix][#55] Indent 수정

@abovocado

2023-11-04 06:34 UTC, xnoag commented on gridy/Sources/Presentations/PlanBoard/RightToolBarView.swift
> +struct RightToolBarView: View {
-확인-

2023-11-04 06:48 UTC, abovocado approved these changes
미반영된 것 수정된 것과 그 외의 개행도 해결된 것 확인했어요! 고생하셨습니다 다들 ^0^

2023-11-04 06:49 UTC, merged