[feat][#63] shareimageview 만들기
DeveloperAcademy-POSTECH/MacC-Team15-Ampersand pull request #64
Opened 2023-11-05 09:07 UTC by Jin-s-work

# Description
close #63 
TimelineLayout에서 Image를 누르면 나오는 공유 모달창을 만들었습니다.
share를 누르면 이미지가 공유되는데, 아직 이미지가 없어 일단 빈 이미지를 통해 공유 모달이 뜨게 하였습니다.
datepicker의 경우 아직 피그마에 디자인이 존재하지 않아서 GraphicalDatePickerStyle로 넣었습니다.

# Screenshots & Demo
https://github.com/DeveloperAcademy-POSTECH/MacC-Team15-Ampersand/assets/61958748/d54bcf4c-88c2-4874-be8c-bb50e0990145

# To Reviewers 🤲
TimelineLayout 창이 나오면 오른쪽 위 이미지 버튼을 누르면 shareimageview가 작동해요
Color를 일단 피그마에서 주어진 대로 item으로 했는데 색이 생각보다 어둡게 나오는거 같아요

2023-11-05 09:14 UTC, xnoag commented on gridy/Sources/ContentView.swift
시뮬레이터로 확인하기 위해서 TimelineLayoutView()로 바꿔놓은 것 같은데, 원래대로 돌려놔주세용

2023-11-05 09:21 UTC, xnoag commented on gridy/Sources/Presentations/PlanBoard/ShareImageView.swift
>  struct ShareImageView: View {
개행

2023-11-05 09:21 UTC, xnoag commented on gridy/Sources/Presentations/PlanBoard/ShareImageView.swift
> +    @State private var isEndDatePickerPresented: Bool = false
타입 추론이 가능하니 :Bool은 제거해주세용

2023-11-05 09:22 UTC, xnoag commented on gridy/Sources/Presentations/PlanBoard/ShareImageView.swift
> +    @State private var isEndDatePickerPresented: Bool = false
타입 추론이 가능합니다~

2023-11-05 09:22 UTC, xnoag commented on gridy/Sources/Presentations/PlanBoard/ShareImageView.swift
> +        VStack(spacing : 16){
`)`와 `{` 사이 띄어쓰기

2023-11-05 09:23 UTC, xnoag commented on gridy/Sources/Presentations/PlanBoard/ShareImageView.swift
> +                .frame(width:436, height:330)
린트 워닝 났을 거에요!
width:(띄어쓰고) 436으로 수정 해주세용

2023-11-05 09:23 UTC, xnoag commented on gridy/Sources/Presentations/PlanBoard/ShareImageView.swift
> +                .overlay(){
()제거

2023-11-05 09:23 UTC, xnoag commented on gridy/Sources/Presentations/PlanBoard/ShareImageView.swift
> +                .overlay(){
`.ovelay {`

2023-11-05 09:25 UTC, xnoag commented on gridy/Sources/Presentations/PlanBoard/ShareImageView.swift
> +                                }
`periodSelection = .setPeriods` 한 줄이라 개행 없이 작성해도 될 것 같아요

2023-11-05 09:28 UTC, xnoag commented
로이스 고생하셨어요! 아직 리뷰 하는 중인데, 린트워닝이 많이 뜹니다.
전반적으로 불필요한 띄어쓰기, 개행, intent 불일치, 필요없는 () 삭제 한 번 수정하고 다시 푸쉬해주세요~!

2023-11-05 10:39 UTC, xnoag commented on gridy/Sources/Presentations/PlanBoard/ShareImageView.swift
> +                                .onTapGesture {periodSelection = .allPeriods}
{ } 사이 띄어쓰기 해주세용

2023-11-05 10:39 UTC, xnoag commented on gridy/Sources/Presentations/PlanBoard/ShareImageView.swift
> +                                .foregroundColor(Color.title)
foregroundStyle

2023-11-05 10:40 UTC, xnoag commented on gridy/Sources/Presentations/PlanBoard/ShareImageView.swift
> +                                .onTapGesture {periodSelection = .setPeriods}
{ } 사이 띄어쓰기 해주세용

2023-11-05 10:40 UTC, xnoag commented on gridy/Sources/Presentations/PlanBoard/ShareImageView.swift
> +                                .foregroundColor(Color.title)
foregroundStyle

2023-11-05 10:43 UTC, xnoag commented on gridy/Sources/Presentations/PlanBoard/ShareImageView.swift
> +                            }
`Button(action: ~` 와 'Button {`로 사용되는데, 통일 해주세용

2023-11-05 10:49 UTC, xnoag requested changes
로이스 고생하셨어요~ 데이트 피커 부분은 디자인 나오면 다시 리팩토링 하면 될 것 같아서, 리뷰 남긴 것만 반영해서 푸쉬 부탁드려욥

2023-11-05 12:16 UTC, Jin-s-work commented
리뷰 해준 대로 코드 다시 짰어요! 세세한 부분 까지 신경써줘서 고마워요 가온 :)

2023-11-05 13:15 UTC, xnoag commented on gridy/Sources/ContentView.swift
로이스 이거 반영이 된 건가요?

2023-11-05 13:15 UTC, xnoag commented on gridy/Sources/Presentations/PlanBoard/ShareImageView.swift
>  struct ShareImageView: View {
로이스 이거 반영이 된 건가요?

2023-11-06 16:30 UTC, dayo2n requested changes
리뷰가 늦었습니다 로이스! 미안해요 😞
전반적으로 접근제어자 지정, 스타일을 통일해 주길 바랍니다 ~!

2023-11-06 16:30 UTC, dayo2n commented on gridy/Sources/Presentations/PlanBoard/ShareImageView.swift
> +/// 한 struct 안에 코드가 너무 길어서 function을 빼려고 했는데 일단은 여기 다 넣어놓겠습니다.
`///`는 코드 설명에 대한 주석으로 사용하기로 했습니다!
추후 추가 처리가 필요한 주석인 경우` // TODO: - `로 작성합니다

2023-11-06 16:30 UTC, dayo2n commented on gridy/Sources/Presentations/PlanBoard/ShareImageView.swift
> +                            .scaledToFit()
정상적으로 캡쳐가 되는 코드가 맞나요?
계속해서 새로운 뷰를 담아주고 있어요 즉 사용자가 플랜을 작성해서 공유하더라도 빈 플랜보드만 계속해서 캡쳐되는 것으로 보입니다
임시로 이렇게 작성한 것인지 궁금하고, 제가 잘못 이해하고 있다면 알려주시길 바랍니다 로이스!

2023-11-06 16:30 UTC, dayo2n commented on gridy/Sources/Presentations/PlanBoard/ShareImageView.swift
> +                            }
```suggestion
                            Button {
                                isStartDatePickerPresented = true
                            } label: {
                                Text("시작 : \(formattedDate(date: selectedStartDate))")
                                    .foregroundStyle(Color.title)
                                    .frame(width: 132, height: 32)
                                    .background(isStartDateHovered ? Color.itemHovered : Color.clear)
                                    .cornerRadius(5)
                                    .onHover { hover in
                                        isStartDateHovered = hover
                                    }
                            }
```
이렇게 스타일을 맞추고 있습니다 ~. ~

2023-11-06 16:30 UTC, dayo2n commented on gridy/Sources/Presentations/PlanBoard/ShareImageView.swift
> +                            }
다른 버튼도 전부 수정 부탁해요!

2023-11-06 16:30 UTC, dayo2n commented on gridy/Sources/Presentations/PlanBoard/ShareImageView.swift
> +    }
흠 .. 방금 가온의 코드에도 같은 리뷰를 달고 왔는데,
이 코드는 이미 릴리가 Date+Extension에 작성해준 똑같은 모양의 코드가 있습니다.
중복 선언되어있는 것이니 삭제하고 기존의 것을 사용해 주세요

2023-11-06 16:30 UTC, dayo2n commented on gridy/Sources/Presentations/PlanBoard/ShareImageView.swift
> +        savePanel.message = "Choose a folder and a name to store the image."
유저에게 보이는 텍스트들 아닌가요?
디자인에서 writing이 안 나왔다면 디자이너분들께 물어보고 일단 다음 작업해달라고 해서 임의의 텍스트가 들어간건지,
물어보지 않았다면 확인 후에 수정바랍니다

2023-11-06 16:30 UTC, dayo2n commented on gridy/Sources/Presentations/PlanBoard/ShareImageView.swift
> +                let renderer = ImageRenderer(content: TimelineLayoutView().environment(\.colorScheme, self.colorScheme))
여기 content에 들어간 parameter도 위에 작성한 코멘트와 마찬가지에요
뷰가 전부 합쳐지면 수정되는거겠죠?

2023-11-06 16:30 UTC, dayo2n commented on gridy/Sources/Presentations/PlanBoard/ShareImageView.swift
> +            if response == .OK, let url = savePanel.url {
조건문에 여러 조건이 들어갈 경우에는 콤마마다 개행하는 것이 어떤가요!
```suggestion
            if response == .OK, 
               let url = savePanel.url {
```

2023-11-06 16:30 UTC, dayo2n commented on gridy/Sources/Presentations/PlanBoard/ShareImageView.swift
> +            print("Error saving image: \(error.localizedDescription)")
그냥 print문은 못보고 지나칠 가능성이 너무 큽니다
원래는 출력문 가장 앞에 ===을 붙이기로 했고, 이모지 등으로 표시해주면 좋겠습니다

예외처리 방법에 대해서는 추후 다시 고민해봅시다 !

2023-11-06 16:30 UTC, dayo2n commented on gridy/Sources/Presentations/PlanBoard/TimelineLayoutView.swift
> +        /// 실제로는 지정되지 않지만 기능 확인하는 용인 frame
기능 확인용이라는건 나중에 필요없어질 코드라는건가요?
여기도 `///` 주석이 아닌 투두 주석이 적절해보입니다.

2023-11-06 16:30 UTC, dayo2n commented on gridy/Sources/gridyApp.swift
> +                TimelineLayoutView()
이건 PR 내용 안에 작성해서 알려주시고 본 코드에서는 변경하지 말아주세요
나중에 이대로 머지될 가능성이 높아보입니다

2023-11-07 00:15 UTC, Jin-s-work commented on gridy/Sources/Presentations/PlanBoard/ShareImageView.swift
> +        savePanel.message = "Choose a folder and a name to store the image."
맞아요!
유저에게 보이는 텍스트라 어떻게 해야 할지 물어보고 일단 이렇게 넣어놓는다고 하였습니다!

2023-11-07 02:31 UTC, Jin-s-work commented on gridy/Sources/Presentations/PlanBoard/TimelineLayoutView.swift
> +        /// 실제로는 지정되지 않지만 기능 확인하는 용인 frame
맞아요 이렇게 원래의 크기를 지정해 놓으면 view를 캡쳐할때 용이합니다.
하지만, frame을 잡으면 크기를 줄일때 줄어들지 않기에 나중에 TimelineLayoutView가 구체화되면 지워야합니다.

2023-11-07 02:47 UTC, Jin-s-work commented
코드 전반적으로 리뷰해줘서 고마워요 제나!
나중에 해결해야 하는 부분들은 아직 Resolve 하지 않을게요.

2023-11-09 15:10 UTC, dayo2n commented
이거 승인하면 되나요? 합친 후에 수정할 예정이죠?

2023-11-09 15:10 UTC, dayo2n approved these changes

2023-11-24 02:07 UTC, dayo2n commented
close with #78

2023-11-24 02:07 UTC, closed without merging