[feat][#62] sheetviews
DeveloperAcademy-POSTECH/MacC-Team15-Ampersand pull request #65
Opened 2023-11-06 08:58 UTC by xnoag

# Description
close #62
LoginView, NotificationView, UserSettingView, CreateFolderView, CreatePlanBoardView, LogoutView, SettingsView, BoardSettingView 뷰 구조를 짰습니다. 
헨리가 TCA 구조로 변환하는 것을 담당해서 하는 게 빠를 것 같다고 하셔서 선 머지 후 상세 고도화 작업 진행할 예정입니다.

# Screenshots & Demo
<img width="489" alt="스크린샷 2023-11-06 오후 5 53 15" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team15-Ampersand/assets/125735850/3536db75-edde-494c-9ed5-b0c635d8a5f0">
<img width="266" alt="스크린샷 2023-11-06 오후 5 53 28" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team15-Ampersand/assets/125735850/5b99a0f8-feea-42d6-a2fa-a85b6c6c85ab">
<img width="464" alt="스크린샷 2023-11-06 오후 5 53 47" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team15-Ampersand/assets/125735850/37770e63-2f9a-4674-9446-a125d1a99163">
<img width="300" alt="스크린샷 2023-11-06 오후 5 53 52" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team15-Ampersand/assets/125735850/4f0aa60a-1224-4179-8ba8-e0cff7800937">
<img width="490" alt="스크린샷 2023-11-06 오후 5 52 50" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team15-Ampersand/assets/125735850/95fc4745-4342-4c53-b659-6ee8d12e11f2">
<img width="292" alt="스크린샷 2023-11-06 오후 5 52 34" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team15-Ampersand/assets/125735850/f2ff182f-edce-4ae5-9616-b4cc82e64720">
<img width="481" alt="스크린샷 2023-11-06 오후 5 52 17" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team15-Ampersand/assets/125735850/fa581c12-ef0e-4869-9541-a204567df4ec">
<img width="609" alt="스크린샷 2023-11-06 오후 5 53 04" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team15-Ampersand/assets/125735850/9e1f19d3-6267-48c3-928e-ada92ae11a14">
<img width="814" alt="스크린샷 2023-11-06 오후 5 55 36" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team15-Ampersand/assets/125735850/55a64e9e-7c18-4fc8-8533-e10463a3e244">

# To Reviewers
주말동안 정신 없이 만드느라, 최대한 깔끔하게 짜려고 했지만 수정해야될 부분이 있을 것으로 보입니다. 가차없이 패주시면 감사하겠습니다.

2023-11-06 16:00 UTC, dayo2n requested changes
proxy, button의 후행클로저 문법 사용은 코드 전반에 대해 수정 바랍니다
TCA를 따르지 않는다고 했으니 @State 프로퍼티의 사용에 대해서는 리뷰하지 않았습니다 !

2023-11-06 16:00 UTC, dayo2n commented on gridy/Resources/Assets.xcassets/LiLyProfile.imageset/스크린샷 2023-11-05 오후 4.09.20 1.png
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2023-11-06 16:00 UTC, dayo2n commented on gridy/Sources/Presentations/PlanBoard/BoardSettingView.swift
> +    }
이건 Date+Extenstion에 이미 똑같은 이름과 코드로 구현되어 있습니다 
삭제하고 기존에 선언되어 있는 것을 사용해 주세요!

2023-11-06 16:00 UTC, dayo2n commented on gridy/Sources/Presentations/PlanBoard/BoardSettingView.swift
>              }
지난 코드리뷰에서 후행클로저에 대한 코멘트를 남긴 적이 있습니다
```suggestion
                Button("Done") {
                    startDatePickerPresented = false
                }
```

2023-11-06 16:00 UTC, dayo2n commented on gridy/Sources/Presentations/PlanBoard/BoardSettingView.swift
> +                })
여기도 수정바랍니다 ~

2023-11-06 16:00 UTC, dayo2n commented on gridy/Sources/Presentations/PlanBoard/BoardSettingView.swift
> +        }
헨리의 코드인가요 가온의 코드인가요?
onHover 공식문서의 Parameters를 보면 전달받는 클로저 인자는 부울형입니다
가온의 코드라면 적절한 이름으로 바꾸어 작성해 주세요
헨리의 코드라도 같이 수정 바랍니다 ㅎ

2023-11-06 16:00 UTC, dayo2n commented on gridy/Sources/Presentations/ProjectBoard/CreatePlanBoardView.swift
> +                    startDateHovered = hover
여기는 둘 다 작성이 잘 되었네요 👍

2023-11-06 16:01 UTC, dayo2n commented on gridy/Sources/Presentations/ProjectBoard/SettingsView.swift
> +    var jobOptions = ["개발자", "디자이너", "기획자", "부자"]
ㅋㅋㅋ부자 ㅋㅋ

2023-11-07 06:47 UTC, xnoag commented on gridy/Sources/Presentations/PlanBoard/BoardSettingView.swift
> +    }
[fix][#62] DateExtension 사용
<img width="262" alt="스크린샷 2023-11-07 오후 3 47 37" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team15-Ampersand/assets/125735850/38e3eef6-d43f-47cc-af76-2bea6596695e">

2023-11-07 06:50 UTC, xnoag commented on gridy/Sources/Presentations/PlanBoard/BoardSettingView.swift
>              }
[fix][#62] Button 수정

<img width="134" alt="스크린샷 2023-11-07 오후 3 49 53" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team15-Ampersand/assets/125735850/45965e9a-a659-4303-94d8-7c9b2c3ef9f1">

2023-11-07 06:54 UTC, xnoag commented on gridy/Sources/Presentations/PlanBoard/BoardSettingView.swift
> +        }
걔온의 코드입니다.
[fix][#62] 모든 proxy를 isHovered로

2023-11-07 06:55 UTC, xnoag commented
<img width="314" alt="스크린샷 2023-11-07 오후 3 55 07" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team15-Ampersand/assets/125735850/6f9e13ca-263c-46d3-b5e2-34f0c1b00cec">

@dayo2n 리뷰 반영 했써요

2023-11-07 08:33 UTC, abovocado requested changes
고생했어요 가온!~!~!~! 이런 구조를 짤 수 있음에 다시한번 놀라움을 금치 못하고 갑니다!

사실 수정해야할 것은 많이 없는 것 같아요. 몇 개 빼고는 질문이 있어서 코멘트 남겨놓았습니다.

확인해보고 코멘트 남겨주세요~! 역가짱가

2023-11-07 08:33 UTC, abovocado commented on gridy/Sources/Presentations/ProjectBoard/CreateFolderView.swift
> +        Button {
같은 모양의 버튼이 텍스트와 액션만 다르게 변경되어 사용되고 있는데 나중일이지만 버튼도 컴포넌트화가 되면 좋겠네요~ 같은 코드를 여러번 쓰지 않아도 되고, 컴포넌트 스타일 관리도 쉬워질 것 같아요!

2023-11-07 08:33 UTC, abovocado commented on gridy/Sources/Presentations/ProjectBoard/CreatePlanBoardView.swift
> +    }
여기는 DateExtension에 있기 때문에 삭제해도 좋겠네요~!

2023-11-07 10:52 UTC, xnoag commented on gridy/Resources/Assets.xcassets/LiLyProfile.imageset/Contents.json
> +      "filename" : "스크린샷 2023-11-05 오후 4.09.20 1.png",
[fix][#62] Lily 제거

2023-11-07 10:52 UTC, xnoag commented on gridy/Sources/Deprecated/ProjectBoardViewDeprecated.swift
> +//
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2023-11-07 10:54 UTC, xnoag commented on gridy/Sources/Deprecated/ProjectBoardViewDeprecated.swift
> +//
[fix][#62] 개행 제거

2023-11-07 10:59 UTC, xnoag commented on gridy/Sources/ContentView.swift
> +            LoginView()
[fix][#62] LoginView -> AuthenticationView Rename

2023-11-07 11:01 UTC, xnoag commented on gridy/Sources/Presentations/Common/LoginView.swift
>  struct LoginView: View {
LoginView는 쩌기 ProjectBoardView에서도 나올 예정이라 Common입니다요!

[fix][#62] AuthenticationView 패딩 수정

2023-11-07 11:02 UTC, abovocado commented on gridy/Sources/Presentations/Common/LoginView.swift
>  struct LoginView: View {
설명 고마워용~

2023-11-07 11:02 UTC, xnoag commented on gridy/Sources/Presentations/Common/LoginView.swift
> +            VStack(spacing: 16) {
예리한 릴리 예릴리~! 제가 PR 전에 고친다고 바꿔버렸는데, 역시 정답은 바꾸기 전 선택이 항상 맞군요

2023-11-07 11:14 UTC, xnoag commented on gridy/Sources/Presentations/ProjectBoard/CreatePlanBoardView.swift
> +    }
[fix][#62] DateFormatter

헐랭 방구, 아까 릴리한테 했다고 자랑하고 스태쉬를 해버렸나봐요 반영했습니다

2023-11-07 11:14 UTC, xnoag commented on gridy/Sources/Presentations/ProjectBoard/CreateFolderView.swift
> +        Button {
맞아요 컴포넌트 필요함!

2023-11-07 11:24 UTC, abovocado approved these changes
100점 만점에 만점 드리겠습니다~! 얏호

2023-11-07 11:30 UTC, dayo2n approved these changes
코멘트남긴거 수정하시고 머지하세요~ 미리 승인남기는거니까 반.드.시. 수정 후에 머지바랍니다 ^^

2023-11-07 11:30 UTC, dayo2n commented on gridy/Sources/Presentations/Common/TabBarView.swift
> +    @Binding var bellButtonClicked: Bool
타입 추론 가능한데 명시해둔거 킹받ㄴㅔ요

2023-11-07 11:30 UTC, dayo2n commented on gridy/Sources/Presentations/ProjectBoard/CreatePlanBoardView.swift
> +                })
```suggestion
                Button("Done") {
                    startDatePickerPresented = false
                }
```

2023-11-07 11:30 UTC, dayo2n commented on gridy/Sources/Presentations/ProjectBoard/CreatePlanBoardView.swift
> +                })
```suggestion
                Button("Done") {
                    endDatePickerPresented = false
                }
```

2023-11-07 11:35 UTC, merged