[feat][#61] PlanBoardView와 ProjectBoardView의 Hover, FocusGroup TCA구조의 코드 작성
DeveloperAcademy-POSTECH/MacC-Team15-Ampersand pull request #66
Opened 2023-11-06 14:31 UTC by OreobrO

# Description
close #[61]
PlanBoardView와 ProjectBoardView의 Hover, FocusGroup TCA구조의 코드 작성을 완료하였습니다.
추후 잔여 작업:
- 기존 ProjectItemView를 PlanBoardItemView에 이전
- 기존 TimelineLayoutView를 PlanBoardView에 이전

# Screenshots & Demo

# To Reviewers 🤲

2023-11-06 15:29 UTC, dayo2n requested changes
속이 뻥 뚫리는 피알입니다!!! 뚫어뻥 🪠
고생 많았어요 헨리 TCA와 더 친해졌기를 바라며 질문 몇가지와 리뷰를 남깁니다 🫠

1. 이전에는 폴더뷰에서 personal project의 토글버튼을 누르면 폴더가 접혔다 펴졌다 했던 것 같은데 동작하지 않습니다. 이 코드에 포함이 되어있지 않는건가요?
2. 아직 남아있는 State 프로퍼티들은 어떻게 처리될 예정이고 남아있는 이유가 무엇인가요 ?!

proxy로 사용하고 있는 Bool 형태의 클로저 인자의 이름을 모두 수정해 주시길 바랍니다~~ (한군데만 코멘트남겼기에 ...)

2023-11-06 15:29 UTC, dayo2n commented on gridy/Sources/Presentations/Common/TabBarView.swift
>              }
아하 이거 아까 말하려다가 proxy가 아닌것같다고 얘기하길래 수정할줄 알고 얘기 안했는데 말이지요
[공식문서](https://developer.apple.com/documentation/swiftui/view/onhover(perform:))의 Parameters 항목을 보면 action 클로저가 true 또는 false를 전달해준다고 명시되어있습니다
헨리가 클로저 인자를 GeometryReader의 content가 넘겨주는 GeometryProxy 타입을 쓰는 것으로 시작해서 습관이 된 것 같아요 네이밍을 정확하게 사용해봅시다용

2023-11-06 15:29 UTC, dayo2n commented on gridy/Sources/Presentations/Common/TabBarView.swift
> +    @State var isDeleteButtonHovered = false
이 아이는 일부러 남겨두었나요 ?

2023-11-06 15:29 UTC, dayo2n commented on gridy/Sources/Presentations/PlanBoard/PlanBoard.swift
> +}
이 아이들도 위치가 여기가 맞을까요 ??
더군다나 이 파일에서만 사용되는 아이들도 아니라서 PlanBoard 내에 선언되는 것보다 String+Extension에 작성하는 것이 맞을 것 같습니다

2023-11-06 15:29 UTC, dayo2n commented on gridy/Sources/Presentations/PlanBoard/PlanBoardView.swift
> +    @State private var timer: Timer?
이것도 무엇이죠 ?,? 안옮겨질 예정인가요 ?? 왜인가요 ?!

2023-11-06 15:29 UTC, dayo2n commented on gridy/Sources/Presentations/PlanBoard/PlanBoardView.swift
> +                            )
개행하고 싶다면 괄호를 열자마자! 닫기 전에도! 괄호 정렬이 안맞네요~!~

2023-11-06 15:29 UTC, dayo2n commented on gridy/Sources/Presentations/PlanBoard/TopToolBarArea.swift
> +                Text("\(tabID)")
tabID는 이미 스트링인데 interpolation 해준 이유가 있나오 ~?~? 텍스트가 추가될 예정인지 ~ 하지만 지금은 tabID뿐인듯한데 !~!

2023-11-06 15:29 UTC, dayo2n commented on gridy/Sources/Presentations/PlanBoard/TopToolBarArea.swift
> +                )
흠 ....🤔 확실히 개선이 필요해보이긴 하네요
일단은 이대로 가고 좋은 코드가 생각나면 꼭 개선합시다 ., ,

2023-11-06 15:29 UTC, dayo2n commented on gridy/Sources/Presentations/ProjectBoard/ProjectBoard.swift
> +}
여기도 ㅇㅣ동 바랍니다 확실히 String 타입으로 선언하면 안되겠다는 생각이 들기는 하네요 흐음~...

2023-11-06 15:45 UTC, OreobrO commented on gridy/Sources/Presentations/Common/TabBarView.swift
>              }
오 proxy는 뭔가 이상하다 싶었는데, 떠먹여주기 감사합니다~

2023-11-06 15:56 UTC, OreobrO commented on gridy/Sources/Extensions/Components.swift
> +}
앞으로 뷰 전반적으로 쓰일 버튼이나 디자인 컴포넌트를 관리하려고하는데 어디가 좋을까요?

2023-11-06 16:01 UTC, OreobrO commented on gridy/Sources/Presentations/Common/TabBarView.swift
> +    @State var isDeleteButtonHovered = false
hoveredItem은 하나만 가능하다는 로직에 위배되는 이 xmark 아이가 조금 골치덩어리라서,,,잠시 냄겨두고자 합니다. 다음 번 TCA 마무리단계에서 분리하겠습니다.

2023-11-06 16:02 UTC, OreobrO commented on gridy/Sources/Presentations/PlanBoard/PlanBoard.swift
> +}
앗  좋습니다.

2023-11-06 16:06 UTC, dayo2n commented on gridy/Sources/Extensions/Components.swift
> +}
아하 View Extension을 생각하고 Extension에 배치했나요 ??
지금 작성되어있는걸론 Utils나 Common이 적절한듯한데 어떤 코드들을 담느냐에 따라 헨리가 선택해서 알려주세요

2023-11-06 16:06 UTC, dayo2n commented on gridy/Sources/Presentations/Common/TabBarView.swift
>              }
푸하하 킹받네요

2023-11-06 16:06 UTC, dayo2n commented on gridy/Sources/Presentations/Common/TabBarView.swift
> +    @State var isDeleteButtonHovered = false
resolve 처리하겠습니다 ~

2023-11-06 16:07 UTC, OreobrO commented on gridy/Sources/Presentations/PlanBoard/PlanBoardView.swift
> +    @State private var timer: Timer?
다음 이슈에서 다룰 예정이랍니다!🥰
이번 머지는 Hover와 click system을 구체화한 내용이구
다음번에는 가온이 ProjectBoardView, 제가 PlanBoardView를 분업해서 완전히 변경하는게 목표~

2023-11-06 16:08 UTC, OreobrO commented on gridy/Sources/Presentations/PlanBoard/PlanBoardView.swift
> +                            )
확인!

2023-11-06 16:09 UTC, OreobrO commented on gridy/Sources/Presentations/PlanBoard/TopToolBarArea.swift
> +                )
넵, 이제 set 항목이 명확히 생겨서, 아침에 시도해본 binding이 유효해진건가 싶긴 한데, 다음 번에 실험 해보죠!

2023-11-06 16:10 UTC, OreobrO commented on gridy/Sources/Presentations/PlanBoard/TopToolBarArea.swift
> +                Text("\(tabID)")
수정완!

2023-11-06 16:12 UTC, OreobrO commented on gridy/Sources/Presentations/ProjectBoard/ProjectBoard.swift
> +}
이동완! FocusGroup과 PopOverButton은 사용자가 변경이 불가능하니, String타입을 가진 enum선언이 가능할 것으로보여요!
근데 이제 Item은 board를 생성할 때 마다 다른 이름이 지정되어서 고민이네요.

2023-11-06 16:18 UTC, OreobrO commented on gridy/Sources/Extensions/Components.swift
> +}
넵! View Extension을 통해 통일된 형태의 텍스트필드나 버튼 등 차차 반영해나갈 예정이에요! 나중에 일부는 구조체 등으로 선언될 뷰인걸 감안하면, common이 일단 적당해보여서 이동하겠습니다.

2023-11-07 02:24 UTC, xnoag commented on gridy/Sources/Presentations/Authentication/AuthenticationView.swift
> +                        radius: 24)
질문 - `)` 위치는 개행하지 않아도 되는 부분일까요??

2023-11-07 02:24 UTC, dayo2n commented on gridy/Sources/Presentations/Authentication/AuthenticationView.swift
> +                        radius: 24)
해야합니닷!-

2023-11-07 02:26 UTC, dayo2n approved these changes

2023-11-07 02:54 UTC, xnoag approved these changes
완벽하네요.. 
리뷰가 하나라서 Approve 하겠습니다. 
`AuthenticationView` 개행만 수정해주시고 머지 해주세요!

2023-11-07 03:02 UTC, merged