[refactor][#54] delete model lane
DeveloperAcademy-POSTECH/MacC-Team15-Ampersand pull request #74
Opened 2023-11-09 14:36 UTC by dayo2n

# Description
close #54 
Lane이라는 모델 구조가 사라진 후 API, Store 코드에서 대공사가 있었습니다.
주로 FirestoreService, APIClient, APIService, PlanBoard 등의 파일이 변경되었습니다.
프론트에서는 PlanBoard에만 접근합니다. 각 액션이 가진 파라미터와 그 동작에 대한 내용은 [노션](https://www.notion.so/apsd/e922cbc20d3f4d3faee6f8b7ca8c45a4?v=de3ffeafabb1475ba820d960cf6103e8&pvs=4)에 명세서를 작성해두었습니다.

# Screenshots & Demo
<img width="1624" alt="스크린샷 2023-11-09 오후 11 34 39" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team15-Ampersand/assets/57654681/3def70df-6ff4-4a85-a481-d4dd6f3351db">

# To Reviewers 🤲
- [ ] tempView는 릴리가 api 동작 확인할 때 사용하던 뷰인데, 저는 이 pr을 올리고 난 후에 테스트해볼 예정이라 일단 남겨두었습니다!

2023-11-09 14:55 UTC, dayo2n commented
내일 오전에 쭉 점검 후에 다시 오픈하겠습니다

2023-11-10 03:46 UTC, xnoag commented on gridy/Sources/Presentations/PlanBoard/PlanBoard.swift
> +                    // !!!: - layer가 #0, #1만 있을 때 사용가능한 로직
`!!!`는 어떨 때 쓰는 건지 알려주시면 감사하겠습니다.

2023-11-10 03:50 UTC, xnoag commented on gridy/Sources/Presentations/PlanBoard/TimelineLayout/TimelineLayoutView.swift
`TCA` 구조로 변환될 파일

2023-11-10 03:50 UTC, xnoag commented on gridy/Sources/Presentations/PlanBoard/tempView.swift
`TCA` 구조로 변환될 파일

2023-11-10 03:54 UTC, xnoag approved these changes
대단합니다. 제나.
2000줄의 코드를 보고 따라치는 것도 엄청난데 이걸 다 생각하고 코드를 치시다니 정말 대단하고 간사합니다.
구두로 전달드린 것(`period`, `// MARK`, `!!!`)외에는 이슈를 발견하지 못했습니다. 최고최고!

2023-11-10 03:54 UTC, xnoag commented
간사x 감사o

2023-11-10 03:57 UTC, dayo2n commented
> 간사x 감사o

ㅋ

2023-11-10 03:58 UTC, dayo2n commented on gridy/Sources/Presentations/PlanBoard/PlanBoard.swift
> +                    // !!!: - layer가 #0, #1만 있을 때 사용가능한 로직
<img width="736" alt="스크린샷 2023-11-10 오후 12 52 11" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team15-Ampersand/assets/57654681/2be74a05-3bbc-44f3-91ec-3af8c30ed877">

2023-11-12 05:15 UTC, abovocado requested changes
... 제 코드가 달라진 것을 보았습니다... 그 와중에 릴리의 코드도 보았다니///!

😭 눈물이 앞을 가리는,,,, 사태,,,

뷰에 액션들이 다 달리면 옛날거라 안쓴는 액션들을 정리하도록 하겠습니다~!^0^

2023-11-12 05:15 UTC, abovocado commented on gridy/Sources/Presentations/PlanBoard/PlanBoard.swift
> +                while !planIDsQ.isEmpty && totalLoop < state.map.count {
고쳐주셨군뇨,,,

2023-11-12 13:12 UTC, OreobrO reviewed
APIService와 PlanBoard reducer에서 불필요한 action의 분기처리를 정리하고 넘어가고자 합니다. 
근데 해당 코드들이 릴리코드인지 제나코드인지 구분이 잘 안되네요!
코멘트에 의견을 남겨두었으니, 한 번 보구 내일 같이 검토 요청드려요.

2023-11-12 13:57 UTC, dayo2n commented on gridy/Sources/Presentations/ProjectBoard/ProjectBoard.swift
> +                    try await apiService.createProject(title, [Date(), Date()])
앗 수정해둘게여 ~~

2023-11-12 14:10 UTC, dayo2n commented on gridy/Sources/Models/Project.swift
@OreobrO 
마지막 수정일로만 정렬될거라고 들어서 createdDate라는 프로퍼티가 삭제된건데 재밌네료...호호
나머지는 지금 있는 정보로 보여줄 수 있으니 createDate 프로퍼티를 롤백하도록 하겠습니다

헨리가 말하는 period와 totalPeriod의 용도와 차이를 모르겠습니다 Plan과 다르지 않나요?
period와 totalPeriod의 차이는 추가로 설명이 필요합니다
아마 플린도 피그마에 같은 질문을 달아뒀었는데, 프로젝트를 생성할 때 지정한 기간에 대해서만 플랜보드가 생성된다고 생각했습니다
<img width="766" alt="스크린샷 2023-11-12 오후 11 08 31" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team15-Ampersand/assets/57654681/fb919132-3f6f-4425-9043-427a4ba8c6a7">

2023-11-12 14:12 UTC, dayo2n commented on gridy/Sources/Models/Project.swift
+ sorting 기준 선택 기능 구현해두겠읍다

2023-11-12 14:16 UTC, dayo2n commented on gridy/Sources/Models/Project.swift
Chronological의 정렬 기준이 어떻게 되는건지도 궁금합니다
period.endDate의 최신순인가요 ??

2023-11-12 14:41 UTC, dayo2n commented on gridy/Sources/Network/FirestoreService.swift
오타인 것 같네요! APIService외에 컬렉션에 접근하는 일은 절대 발생하지 않습니다만 수정하도록 하겠습니다 ~~

2023-11-12 14:51 UTC, dayo2n commented on gridy/Sources/Network/APIService.swift
>          },
@OreobrO 저는 이 유예기간을 주는 기능이 과한 기능이라고 생각해서 상의해보면 좋겠네요
깃헙의 경우, 브랜치를 삭제했을 때 restore 버튼을 눌러 복구가 가능하며, 삭제한 직후 페이지를 벗어나기 전까지 복구가 가능합니다. (새로고침한 이후부터는 복구 불가)
피그마도 마찬가지로 Undo 또는 cmd + z로 되살리기가 가능하고 앱을 리로드하는 경우 복구가 불가능합니다.
아니면 맥과 같이 휴지통을 보여줄 수도 있겠습니다. 이정도가 충분하다고 생각하는데 어떠신지요~~~

deletedProjects Collection은 생성해 두도록 하겠습니다.

2023-11-12 14:52 UTC, dayo2n commented on gridy/Sources/Network/APIService.swift
>          },
가 아니고 deleteProjectCollection에 이미 이동하고 있는 코드네요 ^__^,,

2023-11-12 15:09 UTC, dayo2n commented on gridy/Sources/Presentations/PlanBoard/PlanBoard.swift
> +                    } else {
설명 주석에 작성되어 있는 것처럼 분기처리를 내부에서 한 이유는 dragToMovePlanInList라는 액션에서 createPlanOnList과 동일한 로직이 리턴될 때 실행되어야 합니다. 다만 동일한 플랜타입을 재생성하지 않기 위해서 분기처리를 해둔 것이에요. 
사용자가 내용을 업데이트할 때는 updatePlan, 생성할 때는 createPlanOnList를 호출하는 것으로 이미 분리되어 있습니다.

`사용자가 listArea에서는 기존에 작성되어 있던 planType을 업데이트 하는 행위는 불가능합니다. `라는 내용에 대해서는 상의된 적이 없는 것 같아요 lane 모델이 없어지고 새 디자인이 나오면서 구조가 변경된 것인지 궁금합니다.

line area와 list area의 플랜들이 가지는 plan type이 동일하게 동작하는 게 아니라면 서로 다른 모델과 로직을 가져야 합니다.
헨리가 말한대로 `사용자가 listArea에서는 기존에 작성되어 있던 planType을 업데이트 하는 행위는 불가능`하다면 listArea에서는 title 변경도 불가능한데.. 이게 맞나요??

2023-11-12 15:20 UTC, dayo2n commented on gridy/Sources/Presentations/PlanBoard/PlanBoard.swift
> +                }
사용자 행위에 따라 분리되어 있는 것이 맞습니다.. 사용자가 이미 기존에 있는 title, colorCode로 자동완성뷰에서 선택하지 않고 추가하는 버튼을 눌렀다고 했을 때, 이미 존재하고 있는 type과 동일한 것이 있는지 createPlanType 액션에서 처리하고 있습니다.
동일한 것이 있다면 그제야 APIservice에서 update, 없다면 create를 호출합니다.
개행이 오히려 헷갈리는 코드를 만든듯 한데 updatePlanTypeOnList에서 리턴하면서 호출하고 있는 것은 APIService의 API가 아닌, 다른 액션인 createPlanType을 호출하고 있습니다.

+) 아래 386번줄에 comment 참고는 뭐죠 ?!

2023-11-12 15:24 UTC, dayo2n commented on gridy/Sources/Presentations/ProjectBoard/ProjectBoard.swift
>          case deleteShowingProjects(projectID: String)
@abovocado 릴리의 코드인가요 ?~?

2023-11-12 15:25 UTC, dayo2n commented on gridy/Sources/Presentations/ProjectBoard/ProjectBoard.swift
>          case deleteShowingProjects(projectID: String)
공식 문서에서 navigation 액션에 대한 네이밍을 setNavigation으로 사용하고 있어서 차용한듯합니다
저는 지금도 적절하다고 생각하는데 확인하시고 수정해 주세여~~

2023-11-12 15:26 UTC, dayo2n commented on gridy/Sources/Network/APIService.swift
> +        },
오호 ... 코드는 헨리가 말한대로 구현되어 있는게 맞는데 이름을 바꾸자는 것인지 여쭤봅니다 ~

2023-11-12 16:10 UTC, dayo2n commented on gridy/Sources/Network/APIService.swift
>  }
1. 아하 이 부분 수정하다보니 위 리뷰에서 헨리가 헷갈렸을만한게 제가 작성한 updatePlanType은 updatePlans가 맞습니다. 디자인상에서 plan type의 속성을 right tool bar에서 변경하는 부분이나, 현재 플로우에서 직접 다뤄지지 않고 있던 부분이라 잘못 작성한게 맞네요! 원래는 plan type의 속성을 업데이트하는 api는 없었던 것이 맞습니다 ~

2023-11-12 16:17 UTC, dayo2n commented on gridy/Sources/Network/APIService.swift
>  }
2. 마찬가지로 30일 이내에 복구와 같은 기능에 대해서는 추가 상의가 필요합니다. 불필요한 기능이라고 생각합니다만 위에 코멘트한 것과 같이 cmd+z로 뒤로가기했을 때 휴지통에서 꺼내와야하므로 deleteProjectCollection은 생성해두었습니다. 나머지 컬렉션도 마찬가지로 수정완

2023-11-12 16:21 UTC, dayo2n commented on gridy/Sources/Network/APIService.swift
>  }
3. 위에서는 헨리가 
```
deletePlans: 휴지통으로 이동
deletePlansCompletely: 휴지통으로 넘어가지 않고 돌이킬 수 없이 삭제
```
라고 표현해 두어서 휴지통으로 이동하지 않고 바로 삭제라고 이해했는데, 여기 4번에서는 휴지통 비우기로 표현했는데 여기 말한게 맞는거죠? 그렇다면 휴지통비우기에 대한 api가 delete-Completely인 것이 아니라 휴지통 비우기 액션에서만 이 api를 호출하면 되겠습니다. 플랜을 이동하거나 type을 변경할 때 다른 플랜에 종속되면서 기존 플랜이 소멸되는 경우가 있습니다. 이때 소멸되는 플랜을 아예 삭제하기 위해 만들어둔 API입니다. 껍데기만 있는 코드기때문에 action에서만 잘 사용하면 되겠습니다.

2023-11-12 16:26 UTC, dayo2n commented on gridy/Sources/Presentations/PlanBoard/PlanBoard.swift
> +        case updatePlan(targetPlanID: String, updateTo: Plan)
1. createPlanType은 반드시 어떤 plan을 생성하는 과정 중에 발생합니다. 따라서 파라미터로 어떤 plan에 대한 타입을 변경하는 것인지 알아야 해서 targetPlanID: String을 받아야 합니다.

2023-11-12 16:26 UTC, dayo2n commented on gridy/Sources/Presentations/PlanBoard/PlanBoard.swift
> +        case updatePlan(targetPlanID: String, updateTo: Plan)
2. readPlanTypes에는 파라미터가 불필요합니다.

2023-11-12 16:36 UTC, dayo2n commented
@abovocado 릴리 fetchMap말고,  제일 처음에는 map이 그냥 비어있는 상태이기 때문에 로직 변경이 필요합니다. (state.map.count에 의존해 루프를 돌리는 부분)
그런데 한번 읽어온 후에는 fetchMap의 현재 로직을 사용할 수 있을 것 같고, onAppear할 때 존재하는 plans, planTypes를 읽어오는 액션도 없어서 onAppear에 추가적인 액션이 필요한 것 같아효  read 액션은 제가 할거고 내일 진행상황보고 릴리에게 여유가 있으면 onAppear + fetchMap을 부탁하겠습니다 !-!

2023-11-12 16:42 UTC, dayo2n commented on gridy/Sources/Presentations/PlanBoard/PlanBoard.swift
> +        case updatePlan(targetPlanID: String, updateTo: Plan)
3. 2번에 대한 답변입니다. 위에서 말한 문제랑 같은데, type 자체를 바꾸는 액션은 존재하지 않았습니다. 기존에 작성되어 있던 updatePlanType은 어떤 플랜이 가진 타입을 업데이트하는 액션입니다.
updatePlanTypeOnLine을 구현하기 전에 헨리에게 질문했을 때, 아래 사진에서 선택되어 있는 플랜의 타입을 유저가 변경하면 type 자체의 정보가 업데이트되는 것이 아니라, 선택되어 있는 일자에 대한 플랜만 타입이 바뀐다고 했습니다.
이런 상황이라면 기존 속해있던 플랜에서 해당 period만 떨어지면서 새로운 플랜이 생성됩니다.
<img width="801" alt="스크린샷 2023-11-13 오전 1 38 51" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team15-Ampersand/assets/57654681/c61736d6-8bfd-4c62-a72a-a2ec126b4043">

2023-11-12 16:43 UTC, dayo2n commented on gridy/Sources/Presentations/PlanBoard/PlanBoard.swift
> +        case updatePlan(targetPlanID: String, updateTo: Plan)
4. 1번에 대한 질문입니다. createPlanType이 여러개 작성되어 있었나요?? 타입을 생성하는 액션은 하나뿐이라 예시인지 다른 액션을 두고 남겨준 것인지 여쭤봅니다 ~

2023-11-12 16:44 UTC, dayo2n commented on gridy/Sources/Presentations/PlanBoard/PlanBoard.swift
> +        case updatePlan(targetPlanID: String, updateTo: Plan)
5. 플랜타입을 유저가 삭제하는 플로우가 있나요?

2023-11-12 16:50 UTC, dayo2n commented on gridy/Sources/Presentations/PlanBoard/PlanBoard.swift
> +        case updatePlan(targetPlanID: String, updateTo: Plan)
6. 플랜이나 타입을 동시에 여러개 업데이트할 수 있나요? 프론트에서 표현되는 것도 빡셀듯한데 ...

2023-11-12 16:51 UTC, dayo2n commented on gridy/Sources/Presentations/PlanBoard/PlanBoard.swift
> +        case updatePlan(targetPlanID: String, updateTo: Plan)
7. 사용자가 플랜을 (휴지통으로 이동하지 않고) 바로 삭제하는 플로우가 있나요? 플랜에 휴지통 개념이 있는지도 ~

2023-11-12 16:57 UTC, dayo2n commented on gridy/Sources/Presentations/PlanBoard/PlanBoard.swift
> +        case updatePlan(targetPlanID: String, updateTo: Plan)
8. delete에 관한 액션은 릴리가 맡아주었습니다! 아마도 상황에 따라 로직이 달라서 여러개가 존재해야 할듯 싶은데, 확인해보시고 한 액션에 처리하고 싶다면 릴리와 추후 상의해보면 됩니다 !-!

2023-11-13 01:48 UTC, OreobrO commented on gridy/Sources/Models/Project.swift
기능에 대한 명확한 규정 없이 머릿 속에서만 있는 생각들이 있어서 미안해요 제나.
일단, 프로젝트를 생성할 때 시작과 끝 날짜를 입력할 수 있지만 필수는 아닙니다.
예를 들어 매크로 프로젝트를 생성할 때 9/6~11/24라고 지정하고 시작할 수도 있고, 그냥 지정하지 않고 생성할 수 있는 것이죠.
그러한 의미에서 이는 plan과 비슷합니다. 사용자가 지정한 것이 period, 사용자가 지정하거나 하지 않더라도 항상 본인 내 프로젝트들의 계산된 기간을 갖는 것이 TotalPeriod입니다. 
Chronological은 시작날짜를 기준으로 정순, 역순 정렬을 제공합니다. 사용자 지정기간인 period가 있는 경우 period의 시작날짜,  없는 경우 TotalPeriod의 시작날짜 입니다.
내가 막 이것저것 프로젝트를 만들어왔는데, 인생에 시간순으로 놓고 보았을 때 그 흐름대로 볼 수 있는게 chronological입니다.

2023-11-13 01:53 UTC, OreobrO commented on gridy/Sources/Network/APIService.swift
>          },
저는 협업툴의 관점에서 누군가가 삭제했을 때 복구의 옵션이 있어야한다고 생각합니다. 깃헙은 관리자가 정확한 제목을 정자로 입력해야만 삭제가 가능합니다. 그런데 일반적으로 협업툴에서는 삭제의 플로우가 delete버튼 하나와 같이 심플한 경우가 많습니다. 누군가가 실수나 고의로 삭제했을 때, 이를 발견하고 복구할 수 있는 옵션은 있어야하는데, 현재는 delete가 컬렉션 삭제를 하다보니, 우리도 사용자에게 복구할 수 있는 여지를 주고있지 않습니다. 정보를 홀드하는 기간에 대해서는 30일이라는게 정해진 수치는 아니지만, 우리가 정보를 보관해도 서버 이용량에 문제가 없는 수준과 사용자가 충분히 발견하고 복구를 진행할 수 있는 기간의 조율이 된다면 좋을 것 같습니다.

2023-11-13 01:57 UTC, OreobrO commented on gridy/Sources/Presentations/PlanBoard/PlanBoard.swift
> +                    } else {
사용자가 listArea에서는 기존에 작성되어 있던 planType을 업데이트하는 행위는 불가능합니다. 이는 새로운 구조가 아니라 Update라는 개념에 혼동이 있는 것 같습니다. 헨리라고 적혀있던 list 칸에 제나라고 적는다는 행위는 기존 헨리라는 planType을 업데이트하는 행위가 아닙니다. 헨리라는 planType을 삭제하는 행위도 아니며, 단지 제나라는 planType을 새로 생성하는 행위입니다. planType을 헨리에서 제나로 업데이트해버린다면 리스트에 헨리라고 적힌 것이 모두 제나로 바뀌지 않을까 생각됩니다.

2023-11-13 01:59 UTC, OreobrO commented on gridy/Sources/Presentations/PlanBoard/PlanBoard.swift
> +                }
요 부분도 Update와 create의 역할에 혼선이 있는 듯 합니다. planType의 업데이트는 리스트나 라인의 제목을 바꿈으로써 발생하는 것이 아니라, 객체를 클릭했을 때 툴바에서 해당 planType의 전체 색이나 전체 이름을 바꿀수 있는 기능이 존재할 때만 가능한 행위입니다. 이름을 쓰고 새로운걸 덮어쓰는 것은 같은 항상 Create라고 생각됩니다.

2023-11-13 02:00 UTC, OreobrO commented on gridy/Sources/Network/APIService.swift
> +        },
현재는 deletePlansCompletely가 직접 .plans document에 접근해서 삭제하고 있습니다. 해당 행위를 .deletedPlans의 Document를 삭제하는 것으로 변경하고, 해당 로직은 휴지통에서만 호출하는 것을 제안합니다.

2023-11-13 02:03 UTC, OreobrO commented on gridy/Sources/Presentations/PlanBoard/PlanBoard.swift
> +        case updatePlan(targetPlanID: String, updateTo: Plan)
3. 아하 그러면 UpdatePlan을 호출하여 해당 Plan의 날짜정보를 바꾸고, createPlan으로 새로운 plan이 생성되는 것이라고 생각이 되네요. 선택일자의 plan을 업데이트한다라는 개념에서 오류가 있는 듯 합니다.

6. 라인에서 드래그해서 여러 Plan이 포함된 10칸을 선택하고 삭제하면 그게 여러개를 삭제하거나 업데이트하는 행위라고 생각했습니다.

7. 바로 document삭제는 불가, 휴지통개념이 있는 지도~

2023-11-13 08:19 UTC, abovocado commented on gridy/Sources/Presentations/ProjectBoard/ProjectBoard.swift
>          case deleteShowingProjects(projectID: String)
@OreobrO , @dayo2n 제 코드가 맞습니다~!

현재 내가 보고 있는 탭 이외의 것을 탭바뷰에서 삭제할 수 있어서 delete라는 표현을 썼는데요, projects를 지우는게 아닌데 이름이 저렇게 들어가있어서 헷갈릴 수도 있겠습니다~! deleteShowingTap으로 변경할게요!

set도 open보다는 현재 보여지는 탭을 갈아끼우는 느낌이라 set을 사용했는데 project가 아니라 tap으로 이름을 변경하도록 하겠습니다~!

2023-11-13 16:51 UTC, dayo2n commented on gridy/Sources/Models/Project.swift
사용자 지정 기간이 optional인가요?? 이 부분 명세가 명확하지 않아서 헷갈리네요 ㅠ 아침에 뭐가 옵셔널이라고 얘기해줬는데 이거였나요 ?! 지금은 non-optional로 선언되어 있어서 period의 시간 날짜로 정렬하겠습니다.
그리고 사용자가 선택하는 정렬기준은 Chronological 하나뿐인데 period가 있느냐 없느냐에 따라 보이는 기준이 달라지는 건가요?

2023-11-13 16:52 UTC, dayo2n commented on gridy/Sources/Models/Project.swift
아하 필수는 아니라고 코멘트 시작부분에 있네요 ... 하하하....

2023-11-14 01:46 UTC, xnoag commented on gridy/Sources/Presentations/PlanBoard/tempView.swift
> +                    //                    .padding()
주석 - 릴리한테 얘기했어용

2023-11-14 02:15 UTC, abovocado approved these changes
짱제나!짱제나!짱제나!짱제나!

createPlanOnList에서 PlanType이 바뀌는 경우는 없다고 생각을 했어서 혼선이 있었네요...

제나랑 이야기 하고 이해했습니다!

@OreobrO delete는 상황에 따라 필요한 파라미터와 액선이 달라서 사용자 액션별로 로직을 구분해두었습니다. 혹시 합쳐져야할 부분이 있다고 생각되면 저에게 말씀해주세요~! 저는 어프르부를 드리겠습니당!

2023-11-14 02:17 UTC, merged