67 feat planboardview를 tca구조로 온전히 변환하고 실제 생성되는 plan과 연동하기 전 관련 UI작업을 진행합니다
DeveloperAcademy-POSTECH/MacC-Team15-Ampersand pull request #80
Opened 2023-11-15 13:20 UTC by OreobrO

# Description
close #[이슈번호]
[어떤 기능]을 개발했습니다

# Screenshots & Demo
[Optional] 개발한 기능의 스크린샷이나 gif, 영상

# To Reviewers 🤲
- [ ] @dayo2n 의 LoginView.swift 파일에 충돌이 예상됩니다. 확인 부탁드려요.

2023-11-15 16:08 UTC, dayo2n requested changes
릴리가 고대하던 멋진 스킨이 들어오겠군여 
저도 얼른 이 피알이 머지되어 line area 작업을 하고싶습니닷

2023-11-15 16:08 UTC, dayo2n commented on gridy/Sources/Presentations/PlanBoard/PlanBoardView.swift
> +                                                CGFloat(selectedRange.end.row - viewStore.shiftedRow - viewStore.scrolledRow) * viewStore.lineAreaGridHeight + height / 2)
두 position의 파라미터 선언 위치가 다릅니다. 위에도 콜론 뒤에 개행이 다 있던데
우리 코드 컨벤션에 따르면 이런 규칙은 없고 **괄호를 열자마자, 파라미터마다, 닫기 직전** 개행입니다
두 포지션의 코드가 같은 것 같아서 비교하려고 했는데 개행이 조금씩 달라서 보기 어렵네요!

2023-11-15 16:08 UTC, dayo2n commented on gridy/Sources/Presentations/PlanBoard/PlanBoardView.swift
> +                    }
필요없는 개행이 있습니다!

2023-11-15 16:08 UTC, dayo2n commented on gridy/Sources/Presentations/PlanBoard/PlanBoardView.swift
> +                .onReceive(timer, perform: { _ in
```suggestion
                .onReceive(timer) { _ in
```

2023-11-15 16:08 UTC, dayo2n commented on gridy/Sources/Presentations/PlanBoard/PlanBoardView.swift
> +                .onReceive(timer, perform: { _ in
trailing closure syntax 참고

2023-11-15 16:08 UTC, dayo2n commented on gridy/Sources/Presentations/PlanBoard/PlanBoardView.swift
> +                    default: break
```suggestion
                    default: 
                        break
```

2023-11-15 16:08 UTC, dayo2n commented on gridy/Sources/Presentations/PlanBoard/PlanBoardView.swift
> +                }
액션에서 처리되는것으로 수정된 것 맞죠?! 주석 삭제 ~~

2023-11-15 16:08 UTC, dayo2n commented on gridy/Sources/Presentations/PlanBoard/PlanBoardView.swift
> +                                    )
굳이 nil로 한번 초기화해주는 이유가 있나요 ??

2023-11-15 16:08 UTC, dayo2n commented on gridy/Sources/Presentations/PlanBoard/PlanBoardView.swift
> +                                        end: (endRow + viewStore.shiftedRow + viewStore.scrolledRow, endCol + viewStore.shiftedCol + viewStore.scrolledCol))
개행하는 것이 좋겠습니다

2023-11-15 16:08 UTC, dayo2n commented on gridy/Sources/Presentations/PlanBoard/PlanBoardView.swift
> +                    return event
여기 if문 내부에는 뭐가 들어가나요 ?

2023-11-16 00:39 UTC, OreobrO commented on gridy/Sources/Presentations/PlanBoard/PlanBoard.swift
> +                }
마우스나 키보드로 드래그해서 시작점이 화면에 안보일정도 길어지게 선택한다.
엔터를 클릭한다.
시작점 위치로 스크롤된다.

요 로직이 있습니다!

2023-11-16 00:43 UTC, OreobrO commented on gridy/Sources/Presentations/PlanBoard/CalendarView.swift
xcode에는 안보이고 폴더에 있네요, 삭제완요!

2023-11-16 00:44 UTC, OreobrO commented on gridy/Sources/Presentations/PlanBoard/PlanBoard.swift
> +                plansToUpdate.append(state.existingPlans[merge]!)
YEAP

2023-11-16 00:49 UTC, OreobrO commented on gridy/Sources/Presentations/PlanBoard/PlanBoard.swift
>                      state.shiftedCol = state.selectedGridRanges.last!.start.col - 2
넵, If let 구문으로 감싸주었습니다!

2023-11-16 00:51 UTC, OreobrO commented on gridy/Sources/Presentations/PlanBoard/PlanBoard.swift
> +                    break
넵, default break 처리 완료!

2023-11-16 00:52 UTC, dayo2n commented on gridy/Sources/Presentations/PlanBoard/PlanBoard.swift
> +                }
그러면 위치가 여기가 맞나요? 이 액션은 드래그를 완료한 후에 엔터를 눌러야 호출되는데!!

2023-11-16 00:52 UTC, OreobrO commented on gridy/Sources/Presentations/PlanBoard/PlanBoardView.swift
> +                    default: break
완료!

2023-11-16 00:52 UTC, OreobrO commented on gridy/Sources/Presentations/PlanBoard/PlanBoardView.swift
> +                }
넵!

2023-11-16 00:54 UTC, OreobrO commented on gridy/Sources/Presentations/PlanBoard/PlanBoardView.swift
> +                                    )
그러게요!

2023-11-16 00:55 UTC, OreobrO commented on gridy/Sources/Presentations/PlanBoard/PlanBoardView.swift
> +                                        end: (endRow + viewStore.shiftedRow + viewStore.scrolledRow, endCol + viewStore.shiftedCol + viewStore.scrolledCol))
넵!

2023-11-16 00:55 UTC, OreobrO commented on gridy/Sources/Presentations/PlanBoard/PlanBoardView.swift
> +                    return event
일단 삭제완!

2023-11-16 00:56 UTC, OreobrO commented on gridy/Sources/Presentations/PlanBoard/PlanBoardView.swift
> +                        let date = Calendar.current.date(byAdding: .day, value: dayOffset + viewStore.shiftedCol + viewStore.scrolledCol, to: Date())!
넵!

2023-11-16 00:57 UTC, OreobrO commented on gridy/Sources/Presentations/PlanBoard/PlanBoardView.swift
> +                    }
뺄수있어요! 아얘 메뉴바로 이동하고자해서..바로 다음이슈에서 삭제처리할게요!

2023-11-16 00:58 UTC, OreobrO commented on gridy/Sources/Presentations/PlanBoard/PlanBoardView.swift
> +                            )
뉍!

2023-11-16 00:59 UTC, OreobrO commented on gridy/Sources/Presentations/PlanBoard/PlanBoardView.swift
> +                            let isStartColSmaller: Bool = temporaryRange.start.col <= temporaryRange.end.col
이상하게 얘만 썼네요ㅎㅎ 삭제완료!

2023-11-16 01:01 UTC, OreobrO commented on gridy/Sources/Presentations/PlanBoard/PlanBoardView.swift
> +                                                CGFloat(selectedRange.end.row - viewStore.shiftedRow - viewStore.scrolledRow) * viewStore.lineAreaGridHeight + height / 2)
그렇네요, 모두 컨벤션 규칙으로 변경하겠습니다!

2023-11-16 01:01 UTC, OreobrO commented on gridy/Sources/Presentations/PlanBoard/PlanBoardView.swift
> +                    }
넵!

2023-11-16 01:02 UTC, OreobrO commented on gridy/Sources/Presentations/PlanBoard/PlanBoardView.swift
> +                .onReceive(timer, perform: { _ in
변경완!

2023-11-16 03:28 UTC, dayo2n approved these changes
깔끔하게 모두 잘 반영되었네요^0^ 사소한 오류가 있어 제가 수정해서 커밋했읍니다 캐시때문에 오류없이 돌아갔나보네요 ...

2023-11-17 12:32 UTC, xnoag commented on gridy/Sources/Presentations/PlanBoard/PlanBoardView.swift
> +                                .zIndex(-1)
`zIndex`가 `-1`인 것은 맞게 잘 들어간건가요??
위에서부터 zIndex가 `5`,`4`,`3`,`2`,`-1`이라서 궁금합니당!

2023-11-17 12:38 UTC, xnoag approved these changes
눈에 정말 잘 들어오는 코드입니다!
코드를 좀 오래 보느라 리뷰가 늦었습니다! 저는 이슈를 발견하지 못했어요~
zIndex가 수정이 필요한 부분이라면, 헨리가 반영 후에 머지 해주세요 :)

2023-11-17 13:06 UTC, abovocado commented on gridy/Sources/Presentations/PlanBoard/PlanBoardView.swift
> +                                    )
ㅋㅋㅋㅋㅋㅋ

2023-11-17 14:02 UTC, merged