Feature/75 scheduleline 기능 개발
DeveloperAcademy-POSTECH/MacC-Team15-Ampersand pull request #81
Opened 2023-11-17 02:50 UTC by Jin-s-work

# Description
close #75 
Schedulearea를 개발하였습니다.
그 안에서 ScheduleLine을 만들어서 드래그해서 Enter를 치면 ScheduleLine이 뜨게 만들었고, 밑의 LineArea에서 이동하면서 뷰가 바뀌어도 ScheduleLine은 원래의 좌표에 고정하게 하였습니다.
+ 드래그 해서 선택되는 칸을 파란색으로 표시하게 하는 기능을 LineareaView처럼 만들었습니다.

# Screenshots & Demo
https://github.com/DeveloperAcademy-POSTECH/MacC-Team15-Ampersand/assets/61958748/4710c29d-b600-4848-82b5-e1f4e59d3e03

# To Reviewers 🤲
- 실행해서 확인하기 위해서는 PlanBoardView에서 
<img width="397" alt="스크린샷 2023-11-17 오전 11 27 00" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team15-Ampersand/assets/61958748/61ffa446-a39f-4982-8c6d-a26d67c04746">
를 설정하면 볼 수 있습니다.
.
.
또한, Linearea에서 움직이면서 뷰가 바뀌는 것을 확인하기 위해서는 LineareaView에 
<img width="777" alt="스크린샷 2023-11-17 오전 11 49 18" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team15-Ampersand/assets/61958748/cedafd9c-350f-4162-8337-b1a6eaaff13a">
를 넣어서 첫째 열, 첫째 행에 색을 입혀서 움직이는 것을 확인할 수 있습니다.

2023-11-17 13:35 UTC, xnoag commented on gridy/Sources/gridyApp.swift
> +
여기 실수로 엔터가 눌러졌나봐요! 줄 하나 삭제 부탁드려용

2023-11-17 13:39 UTC, xnoag commented on gridy/Sources/Presentations/PlanBoard/PlanBoard.swift
>              switch action {
switch와 아래 case가 indent가 맞지 않아서, 린트워닝이 뜹니다~

PlanBoard.swift 들어가서 `command + A` 하고 `control + I` 눌러서 전체 정렬 한 번 맞춰주세요!

2023-11-17 14:07 UTC, xnoag commented on gridy/Sources/Presentations/PlanBoard/TimelineLayout/LineAreaView.swift
> +                            .keyboardShortcut(.escape, modifiers: [])
요기도 실수로 스페이스바가 눌러진 . 것같습니다

2023-11-17 14:09 UTC, xnoag commented on gridy/Sources/Presentations/PlanBoard/TimelineLayout/ScheduleAreaView.swift
> +}
@dayo2n 
제나씨~ View파일 안에있는 이 구조체를 View 파일 내부에서 관리하는 게 좋을지, 모델 폴더에 넣어놓는 게 좋을지 궁금해요

2023-11-17 14:10 UTC, dayo2n commented on gridy/Sources/Presentations/PlanBoard/TimelineLayout/ScheduleAreaView.swift
> +}
이 뷰에서만 사용되는 것이라면 뷰 내부에서 관리하는 것이 더 좋겠습니다 !-!

2023-11-17 14:21 UTC, xnoag commented on gridy/Sources/Presentations/PlanBoard/TimelineLayout/ScheduleAreaView.swift
> +                    .hidden()
```suggestion
       Button  {
                        guard let tempRange = scheduleTemporarySelectedGridRange else { return }
                        let startRow = tempRange.start.row
                        let startCol = tempRange.start.col + viewStore.shiftedCol
                        let endCol = tempRange.end.col + viewStore.shiftedCol
                        let newLine = DrawnLine(startRow: startRow, startCol: startCol, endRow: startRow, endCol: endCol)
                        self.completedLines.append(newLine)
                        viewStore.send(.addCompletedLine(newLine))
                        scheduleTemporarySelectedGridRange = nil
                        self.drawingLine = nil
                    } label: {
                        EmptyView()
                    }
                    .keyboardShortcut(.defaultAction)
                    .hidden()
```
위처럼 괄호를 최소화해서 가독성을 높일 수 있도록 작성하면 좋대요!

2023-11-17 14:21 UTC, xnoag commented on gridy/Sources/gridyApp.swift
> +
실수로 엔터가 쳐졌나봐요~ 수정 부탁드립니다~

2023-11-17 14:22 UTC, xnoag requested changes
로이스 아까 카톡으로 전달드린 부분까지 반영해서 푸쉬부탁드립니다~ 고생하셨어요!!

2023-11-17 14:23 UTC, xnoag commented
로이스~ 헨리꺼가 Merge가 되면서, 로이스 파일에 충돌이 생긴 것 같아요.
로이스 브랜치에서 `git pull origin develop --no-rebase` 해서 Develop 브랜치를 풀 받고, 충돌 해결한 후에 위 리뷰사항들 반영해서 푸쉬해주시면 감사하겠습니다!

2023-11-17 17:36 UTC, Jin-s-work commented
다시 rebase로 pull 받고 충돌 해결해서 푸쉬하겠습니다. 정성스러운 리뷰 고마어요 가온~

2023-11-17 17:38 UTC, Jin-s-work commented on gridy/Sources/Presentations/PlanBoard/TimelineLayout/ScheduleAreaView.swift
> +                    .hidden()
action 없이 최소화하는 부분 통일하기로 했었는데 또 넣어버렸네요.. 지적해줘서 고마어요 가온 👍

2023-11-19 08:31 UTC, Jin-s-work commented
원래까지 했던 부분 PlanBoardView에 넣었습니다.
하지만, Enter를 누르면 선을 생성하는 방법 중에 Enter를 눌러서 되는 기능이 될때가 있고 안될때가 있어서 일단 "Command + S"를 누르면 되게 하게 설정하였습니다. 완전하게 Enter를 누르면 될 수 있도록 코드를 바꾸어서 다시 Push 하겠습니다. View도 색이 지금 달라서 고쳐서 다시 commit 하도록 할게요

2023-11-19 08:43 UTC, abovocado commented
로이스~! 지금 코드 리뷰를 하려고 하는데, Enter되면 가능한거랑 색 변경은 이번 PR에 들어가게 되는걸까요? 그렇담 그 이후에 리뷰하고 그게 아니라 새로운 이슈를 파서 작업하는거라면 지금 리뷰하려고요~! @Jin-s-work

2023-11-19 08:45 UTC, Jin-s-work commented
사실 Enter가 되면 되게 하는 것은 keyboardshortcut에서 .defaultAction을 설정하면 되는 간단한 부분인데 지금 안되어서 조금 더 찾아볼 예정이구 색과 hover는 방금 Commit 해서 작동합니다!

2023-11-19 11:03 UTC, abovocado requested changes
로이스 고생했어요~! 빨리 스케줄 AreaView도 들어왔으면~!

1. 전체적으로 indent가 다 안으로 들어가있음 수정 필요!!
2. 삭제된 뷰 파일 Finder에서 삭제하기
3. view에 남아있는 State변수들 Store로 옮기기

이뤄지면 다시 확인하겠습니다~!~! 예에~

2023-11-19 11:03 UTC, abovocado commented on gridy/Sources/Presentations/PlanBoard/PlanBoard.swift
> +
왜인진 모르겠는데 case가 다 indent가 안으로 들어가있어서 모두 수정된 코드라고 나오네요...
cmd + a, ctrl + i로 인덴트 맞추고 다시 push 올리면 추가된 코드 확인하겠습니다!

2023-11-19 15:13 UTC, Jin-s-work commented
정성스레 리뷰 해줘서 고마어요 릴리
lineArea 부분은 제 코드가 아니라 혹시 해서 건들지 않았는데 말한 부분 고치도록 하겠습니다!

2023-11-27 07:10 UTC, dayo2n commented
close with #93

2023-11-27 07:10 UTC, closed without merging