[feat][#72] listArea to TCA
DeveloperAcademy-POSTECH/MacC-Team15-Ampersand pull request #85
Opened 2023-11-18 08:33 UTC by abovocado

# Description
72번 이슈는 닫지 않습니다!
1. projectDelete
2. createPlanOnList
3. updatePlanOnList
4. deletePlanOnList
5. createLayer
6. deleteLayer
7. deleteLayerContents
8. deleteLaneContents
9. rootPlan을 PlanBoard store에서 제거 > 그에 따라 fetchRootPlan 액션 삭제

======
추후 작업할 내용은
1. click 뷰 flow
2. drag 뷰 및 그에 따른 여러 plan 수정 가능한 액션
3. createLane 및 그에 따른 plan 높이 조정
4. deleteLaneOnLine
5. deletePlanOnLine

뷰 작업 완료 및 액션 달기 완료할 예정입니다.

# Screenshots & Demo

https://github.com/DeveloperAcademy-POSTECH/MacC-Team15-Ampersand/assets/102544840/fff8a2b4-57af-4e51-a140-1e0ff2f21295

# To Reviewers 🤲
- [ ] @dayo2n rootPlan을 지우면서 제나의 코드에도 수정이 생겼습니다. 이 부분 꼭! 확인부탁드려요!
- [ ] @xnoag 코드리뷰 마스터 가온에게. timeSleep이 아마 2로 되어있을겁니다. 2초 뒤에 action 확인 부탁해요!

2023-11-18 09:01 UTC, xnoag commented on gridy/Sources/Presentations/PlanBoard/PlanBoard.swift
> +                        state.listAreaHoveredCellCol = Int(state.listAreaHoveredCellLocation.x / 150)
List의 Layer 각 너비가 150으로 지정을 해도 괜찮을까요?

<img width="346" alt="스크린샷 2023-11-18 오후 6 00 01" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team15-Ampersand/assets/125735850/7d2699b5-2cc4-42ec-9e5c-97d2160e3c59">

PlanBoardView에서 영역의 너비를 `150 * CGFloat(viewStore.map.count)`으로 지정하고 있는데, 영역의 너비를 바꿨을 때 동시 수정이 자동으로 가능하게 하려면, 변수화를 하는 건 어떤지 제안드립니다~!

2023-11-18 09:03 UTC, xnoag commented on gridy/Sources/Presentations/PlanBoard/PlanBoardView.swift
> +                        .frame(width: 150 * CGFloat(viewStore.map.count))
`PlanBoard.swift` 파일에서 제안드린 것과 같은 부분입니다!

2023-11-18 09:06 UTC, xnoag commented on gridy/Sources/Presentations/PlanBoard/PlanBoardView.swift
> +                                .opacity(viewStore.selectedLineIndexRow == nil ? 1 : 1)
`viewStore.selectedLineIndexRow == nil ? 1 : 1` 릴리의 귀여운 실수 김발견.

`돈있냐 ? 돈내놔 : 돈내놔` 같은 느낌이군요 ㅎ

2023-11-18 09:07 UTC, xnoag commented on gridy/Sources/Presentations/PlanBoard/PlanBoardView.swift
> +                                          y: CGFloat(Double(hoveredRow) + 0.5) * viewStore.lineAreaGridHeight - viewStore.rowStroke / 2)
개행은
(
블라
블라
)
이렇게 돼야한다고 혼났어요 저.

2023-11-18 09:08 UTC, xnoag commented on gridy/Sources/Presentations/PlanBoard/PlanBoardView.swift
> +                                      y: CGFloat(Double(clickedRow) + 0.5) * viewStore.lineAreaGridHeight - viewStore.rowStroke / 2)
frame만 챙기지말고, position 개행도 챙겨주세요. 포지션 삐짐

2023-11-18 09:10 UTC, xnoag commented on gridy/Sources/Presentations/PlanBoard/PlanBoardView.swift
> +                                          y: CGFloat(Double(hoveredRow) + 0.5) * viewStore.lineAreaGridHeight - viewStore.rowStroke / 2)
요기두~

2023-11-18 09:10 UTC, xnoag commented on gridy/Sources/Presentations/PlanBoard/PlanBoardView.swift
> +                                          y: CGFloat(Double(hoveredRow) + 0.5) * viewStore.lineAreaGridHeight - viewStore.rowStroke / 2)
포지션에게만 엄격한 릴리

2023-11-18 09:11 UTC, xnoag commented on gridy/Sources/Presentations/PlanBoard/PlanBoardView.swift
> +                            .position(x: CGFloat(Double(columnOffset) + 0.5) * 150 - viewStore.columnStroke / 2, y: CGFloat(Double(rowOffset) + 0.5) * viewStore.lineAreaGridHeight - viewStore.rowStro
: )

2023-11-18 09:12 UTC, xnoag commented on gridy/Sources/Presentations/PlanBoard/PlanBoardView.swift
> +                                        .fill(viewStore.listAreaHoveredCellCol == layerIndex && viewStore.listAreaHoveredCellRow == rowIndex ? Color.itemHovered : Color.listArea)
개행이 필요할 지도?

2023-11-18 09:15 UTC, xnoag commented on gridy/Sources/Presentations/PlanBoard/PlanBoardView.swift
> +                                        }
릴리 이 부분 있짜나요.
지금은 `두번탭`만 있는데, 나중에 `한번탭`도 코드가 추가될 예정일까요 ?-?
저도 `한번탭은 count: 1`, `두번탭은 count: 2`로 구분했더니, `한번탭`이 안먹히더라구요!
그래서 아래와 같이 바꿨던 경험이 있어요. 참고해주시면 나중에 `오잉?`하지 않을 것 같네요 :-)

<img width="390" alt="스크린샷 2023-11-18 오후 6 13 07" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team15-Ampersand/assets/125735850/9e7f909a-fbf3-4ec1-b608-4ef03f0bab39">

2023-11-18 09:18 UTC, xnoag requested changes
릴리 최고. 아까 카톡으로 발견한 부분 전달드렸는데, 확인해주시고 반영해주시면 감사하겠습니다!!
동영상에 목소리가 첨부되어있으니,, !

2023-11-18 09:21 UTC, abovocado commented on gridy/Sources/Presentations/PlanBoard/PlanBoard.swift
> +                        state.listAreaHoveredCellCol = Int(state.listAreaHoveredCellLocation.x / 150)
오 좋아요~! 지금 하위뷰에서도 사용이 되고 있기 때문에...!

2023-11-18 09:26 UTC, abovocado commented on gridy/Sources/Presentations/PlanBoard/PlanBoardView.swift
> +                        .frame(width: 150 * CGFloat(viewStore.map.count))
뷰에도 동일하게 적용완료!

2023-11-18 09:30 UTC, abovocado commented on gridy/Sources/Presentations/PlanBoard/PlanBoardView.swift
> +                                .opacity(viewStore.selectedLineIndexRow == nil ? 1 : 1)
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ  돈을 줄. ㅜ밖에 없군요 반영 완료!

2023-11-18 09:31 UTC, abovocado commented on gridy/Sources/Presentations/PlanBoard/PlanBoardView.swift
> +                                          y: CGFloat(Double(hoveredRow) + 0.5) * viewStore.lineAreaGridHeight - viewStore.rowStroke / 2)
헉 혼나기 전 반영 완료!

2023-11-18 09:31 UTC, abovocado commented on gridy/Sources/Presentations/PlanBoard/PlanBoardView.swift
> +                                      y: CGFloat(Double(clickedRow) + 0.5) * viewStore.lineAreaGridHeight - viewStore.rowStroke / 2)
여기두!~@

2023-11-18 09:31 UTC, abovocado commented on gridy/Sources/Presentations/PlanBoard/PlanBoardView.swift
> +                            .position(x: CGFloat(Double(columnOffset) + 0.5) * 150 - viewStore.columnStroke / 2, y: CGFloat(Double(rowOffset) + 0.5) * viewStore.lineAreaGridHeight - viewStore.rowStro
'_'

2023-11-18 09:33 UTC, abovocado commented on gridy/Sources/Presentations/PlanBoard/PlanBoardView.swift
> +                                        .fill(viewStore.listAreaHoveredCellCol == layerIndex && viewStore.listAreaHoveredCellRow == rowIndex ? Color.itemHovered : Color.listArea)
희희 동의보감

2023-11-18 09:34 UTC, abovocado commented on gridy/Sources/Presentations/PlanBoard/PlanBoardView.swift
> +                                        }
반영하고 TODO도 달아놨어요~!@ 고마워요 짱가씨~!

2023-11-18 09:37 UTC, abovocado commented on gridy/Sources/Presentations/PlanBoard/PlanBoardView.swift
> +                                          y: CGFloat(Double(hoveredRow) + 0.5) * viewStore.lineAreaGridHeight - viewStore.rowStroke / 2)
ㅋㅋㅋㅋㅋㅋㅋ

2023-11-18 09:58 UTC, xnoag approved these changes
빠른 리뷰 반영 엄청납니다.
시뮬레이터에서 아까 카톡 영상 이슈 해결된 것도 확인했습니다.
어프루우브

2023-11-20 00:30 UTC, dayo2n approved these changes
릴리의 엄청난 노고가 보입니다 ... 가온과 주말에 열일하느라 너무 고생많았어요~
크게 문제가 되는 코드는 없던 것 같아서 승인남기니 스타일과 중복선언된 바인딩은 꼭 수정해주시고 머지바랍니다~

2023-11-20 00:30 UTC, dayo2n commented on gridy/Sources/Presentations/PlanBoard/PlanBoard.swift
> +        @BindingState var keyword = ""
키워드가 BindingState로 선언되어야 하는 이유가 무엇이었을까요 ?!

2023-11-20 00:30 UTC, dayo2n commented on gridy/Sources/Presentations/PlanBoard/PlanBoard.swift
>                  }
리턴할 때까지 tempLayer와 planIDsQ를 어딘가에 초기화해주는 곳이 없는데 동작이 이게 다가 맞나요 ??
잠시 넣었다 빼기 위한 구조도 아닌것같아 질문합니다~

2023-11-20 00:30 UTC, dayo2n commented on gridy/Sources/Presentations/PlanBoard/PlanBoardView.swift
> +                                .opacity((viewStore.selectedEmptyRow == hoveredRow)&&(viewStore.selectedEmptyColumn == hoveredCol) ? 0 : 1)
```suggestion
                                .opacity((viewStore.selectedEmptyRow == hoveredRow) && (viewStore.selectedEmptyColumn == hoveredCol) ? 0 : 1)
```

2023-11-20 00:30 UTC, dayo2n commented on gridy/Sources/Presentations/PlanBoard/PlanBoardView.swift
> +                    if let columnOffset = viewStore.selectedEmptyColumn, let rowOffset = viewStore.selectedEmptyRow {
```suggestion
                    if let columnOffset = viewStore.selectedEmptyColumn, 
                    let rowOffset = viewStore.selectedEmptyRow {
```

2023-11-20 00:30 UTC, dayo2n commented on gridy/Sources/Presentations/PlanBoard/PlanBoardView.swift
> +                                .focused($listItemFocused)
이 부분 때문에 BindingState로 변경되었군요~ 저도 궁금했던 건데 내친 김에 찾아보았습니다
state를 binding 가능한 형태로 만들 수 있는 방법이 여러가지가 있는데, 이 코드에서는 명시적으로 binding 액션을 선언해주고 있어 텍스트가 바뀔때마다 .keywordChanged가 실행되어 값이 업데이트 될 수 있습니다!
그리고 @BindingState를 사용한다면 이 코드에서는 아래와 같이 코드를 작성해야 합니다
```suggestion
                                TextField("editing",
                                          text: viewStore.$keyword
                                          ))
                                .focused($listItemFocused)
```
문제가 된다기보다는 중복으로 사용하고 있는 상태입니다 !-! 개행까지 수정한다면 아래처럼 쓸 수 있겠네용~
```suggestion
                                TextField(
                                          "editing",
                                          text: viewStore.$keyword
                                          )
                                 )
                                .focused($listItemFocused)
```

https://pointfreeco.github.io/swift-composable-architecture/1.0.0/documentation/composablearchitecture/bindings/
공식문서를 보면 더 이해가 쉬울 것 같습니다 참고 🫰

2023-11-20 00:30 UTC, dayo2n commented on gridy/Sources/Presentations/PlanBoard/PlanBoardView.swift
> +                                                      ))
여기도 개행을 부탁합니다

2023-11-20 00:30 UTC, dayo2n approved these changes
릴리의 엄청난 노고가 보입니다 ... 가온과 주말에 열일하느라 너무 고생많았어요~
크게 문제가 되는 코드는 없던 것 같아서 승인남기니 스타일과 중복선언된 바인딩은 꼭 수정해주시고 머지바랍니다~

2023-11-20 00:30 UTC, dayo2n commented
헉 제 언급을 이제 봤네여~ 쏘리 🍎

2023-11-20 00:35 UTC, abovocado commented on gridy/Sources/Presentations/PlanBoard/PlanBoardView.swift
> +                                .opacity((viewStore.selectedEmptyRow == hoveredRow)&&(viewStore.selectedEmptyColumn == hoveredCol) ? 0 : 1)
반영 완료!

2023-11-20 00:36 UTC, abovocado commented on gridy/Sources/Presentations/PlanBoard/PlanBoardView.swift
> +                    if let columnOffset = viewStore.selectedEmptyColumn, let rowOffset = viewStore.selectedEmptyRow {
반영완료!

2023-11-20 01:27 UTC, abovocado commented on gridy/Sources/Presentations/PlanBoard/PlanBoard.swift
> +        @BindingState var keyword = ""
createProject할 때에도 title을 바꾸는 부분이 있는데, 거기에는 @BindingState 선언을 하지 않고 titleChanged를 불러주고 있더라고요~! 통일성을 위해 @BindingState로 선언했던 부분을 삭제하려고 합니다!

2023-11-20 01:28 UTC, abovocado commented on gridy/Sources/Presentations/PlanBoard/PlanBoardView.swift
> +                                .focused($listItemFocused)
개행완료~!

2023-11-20 01:28 UTC, abovocado commented on gridy/Sources/Presentations/PlanBoard/PlanBoardView.swift
> +                                                      ))
개행완료~!

2023-11-20 01:55 UTC, abovocado commented on gridy/Sources/Presentations/PlanBoard/PlanBoard.swift
>                  }
아하 여기는 delete된 Plan과 그 하위 Plan들을 마지막 depth까지 검사하여 deletedPlan이라는 배열에 넣어주는 코드인데요,

planIDsQ와 tempLayer라는 변수는 그 로직을 위해 존재하는 변수들입니다.
그래서 deletedPlan에 삭제할 Plan들을 담아주면 사실 필요없는 친구들이고요,,,

`planIDsQ.removeAll()
  planIDsQ.append(contentsOf: tempLayer)
  tempLayer.removeAll()`

이 코드에서 planIDsQ와 tempLayer가 비워졌다가 planIDsQ에 tempLayer에 속해있는 원소들이 옮겨지긴 합니다~! 
planIDsQ = [], tempLayer = []로 고쳐놓도록 하겠습니다!

2023-11-20 02:04 UTC, merged

2023-11-20 17:03 UTC, dayo2n commented on gridy/Sources/Presentations/PlanBoard/PlanBoard.swift
>                  }
릴리 여기 바뀐 로직을 제대로 확인해보지 않았는데 변경된 코드가 잘못된듯합니다
일단 롤백만 해두었어요

2023-11-20 17:03 UTC, dayo2n commented on gridy/Sources/Presentations/PlanBoard/PlanBoard.swift
>                  }
@abovocado