[feat][#86] WindowButton과 TabBarView 맞추기
DeveloperAcademy-POSTECH/MacC-Team15-Ampersand pull request #90
Opened 2023-11-21 15:50 UTC by Jin-s-work

# Description
close #86 
- Window Button을 원래 커스텀해서 만들다가 원래의 Window Button과 TabBarView를 함께 써야 하는 것을 깨달아서 함께 나오게 하였습니다.
- ToolBar를 만들어서 Window Button의 위치를 맞추었고, 최대화를 할 경우 ToolBar를 없애서 TabBarView만 맨 위에 나오게 하였습니다.
- 최대화의 경우 windowSize를 계산해서 최대화가 되었을때 ToolBar를 없앴습니다. 그러고 다시 최대화를 해제하는 경우 ToolBar를 만들었습니다.
- 또한, 최대화를 하였을때 Window Button이 없어질 경우 그 공간이 없어지기에 최대화가 되지 않았을 경우에만 Spacer를 넣어서 Window Button과 맞추어주었습니다.

# Screenshots & Demo
처음 창을 띄웠을때는 Window Button과 TabBarView과 함께 있습니다. (ToolBar를 만들어서)
<img width="990" alt="스크린샷 2023-11-22 오전 12 41 42" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team15-Ampersand/assets/61958748/e2919dd8-f12e-47a4-a5fd-f3c206532a8a">
<br>
최대화를 할 경우에는 Window Button이 없어지고 원래의 탭들이 앞으로 옵니다. (ToolBar를 다시 nil로 만들어서 없앱니다.)
<img width="2559" alt="스크린샷 2023-11-22 오전 12 42 14" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team15-Ampersand/assets/61958748/c02c47d4-27bd-4430-b95d-8b8c8267f67b">
<br>
다시 최대화를 해제할 경우에는 처음처럼 다시 돌아옵니다. (ToolBar를 다시 만듭니다.)
<img width="990" alt="스크린샷 2023-11-22 오전 12 41 42" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team15-Ampersand/assets/61958748/a96bf913-e877-47c0-bab5-e79c33b1848b">

# To Reviewers 🤲

2023-11-24 02:26 UTC, dayo2n requested changes

2023-11-24 02:26 UTC, dayo2n commented on gridy/Sources/ContentView.swift
> +
개행은 갑자기 왜 생겼는지~?

2023-11-24 02:26 UTC, dayo2n commented on gridy/Sources/gridyApp.swift
> +    @Published var isMaximized = false
안쓰이는 프로퍼티같은데요??

2023-11-24 02:26 UTC, dayo2n commented on gridy/Sources/Presentations/ProjectBoard/ProjectBoardView.swift
> +                    ))
프로젝트보드에서 프로젝트 삭제하면 여기서 오류날텐데 수정해둔 코드를 왜 롤백되었죠

2023-11-24 02:26 UTC, dayo2n commented on gridy/Sources/gridyApp.swift
> +}
아직도 MVVM으로 코드가 올라오고 있네요...

2023-11-24 02:49 UTC, dayo2n commented on gridy/Sources/gridyApp.swift
> +}
아뇨 ... 이 놈은 일단 이렇게 가도록 하겠읍니다
엔트리부터 있는 것이라 스토어에 이식하기 쉽지 않은 것이 맞네요!!

2023-11-24 02:57 UTC, dayo2n approved these changes

2023-11-24 03:22 UTC, dayo2n commented
확인완료된 피알이니 승인나면 바로 머지하셔도 됩니다~

2023-11-27 07:10 UTC, xnoag approved these changes
(남)승인
고등학교 친구이름.

2023-11-27 07:10 UTC, merged