[feat][#88] ScheduleArea View CRUD
DeveloperAcademy-POSTECH/MacC-Team15-Ampersand pull request #93
Opened 2023-11-24 03:00 UTC by xnoag

# Description
close #88
1. [ProjectBoardView]에서 [원탭과 더블탭] 적용해놨습니다.
2. ScheduleArea View CRUD 작업을 진행했습니다.

# Screenshots & Demo
1. https://github.com/DeveloperAcademy-POSTECH/MacC-Team15-Ampersand/assets/125735850/0afd5564-5f6b-42ea-94f3-63ce25a4f6e1
2. https://github.com/DeveloperAcademy-POSTECH/MacC-Team15-Ampersand/assets/125735850/eff48ca9-5de6-44de-88ff-a8c2a1c70bb4

# To my lovely Reviewers
1. 들어가있는 기능은 CRUD 그 자체입니다. 그 외 디테일한 부분은 새로 이슈를 파서 작업하겠습니다.
2. Schedule의 Row는 3개가 최대입니다. 4개 이상일 때의 디자인의 반영과 로직 수정은 다음에 이슈를 파서 작업하겠습니다.
3. Schedule의 이동과 수정에서 바로 움직이는 것이 아닌 temporary로 미리보기가 보여지는 등의 작업도 이슈 파서 작업하겠습니다.

2023-11-24 03:18 UTC, xnoag commented on gridy/Sources/Models/Schedule.swift
> +    static let mock = Schedule(id: "", title: "", startDate: Date(), endDate: Date(), colorCode: 0x000000, category: ScheduleCategory.none.rawValue)
개행하겠습니다.

2023-11-24 03:19 UTC, xnoag commented on gridy/Sources/Presentations/PlanBoard/PlanBoard.swift
> +        var updateSchedulePresented = false
코드 위치 변경하겠습니다.

2023-11-24 03:21 UTC, xnoag commented on gridy/Sources/Presentations/ProjectBoard/ProjectBoardView.swift
> +                    )
개행을 취소하겠습니다.

2023-11-25 11:48 UTC, dayo2n approved these changes
오타정도를 제외하고는 특별히 문제될만한 것들을 발견하지 못했습니다
새삼 기능 하나를 온전히 구현할 수 있을정도로 성장했음이 느껴져 대단하네요
물론 많은 도움을 줬을 릴리가 함께했지만~🌼 수고했습니다 가온
코멘트드린 것들만 수정해주시면 되겠습니다
단축키건에 대해서는 한번에 처리하도록 하겠습니다

2023-11-25 11:48 UTC, dayo2n commented on gridy/Sources/ContentView.swift
> +//            ._printChanges()
없으면 상태변경이 어떻게 나오는지 로그가 안찍히지 않나요 ?~? 삭제할거면 아예 삭제해도 되겠습니다

2023-11-25 11:48 UTC, dayo2n commented on gridy/Sources/Models/SelectedScheduleRange.swift
> +    }
startCol과 endCol도 모두 비교하는 것이 좋겠습니다

2023-11-25 11:48 UTC, dayo2n commented on gridy/Sources/Presentations/PlanBoard/PlanBoard.swift
> +        case dragExceededSchedule(shiftedCl: Int, exceededCol: Int)
오타 발견!
```suggestion
        case dragExceededSchedule(shiftedCol: Int, exceededCol: Int)
```

2023-11-25 11:48 UTC, dayo2n commented on gridy/Sources/Presentations/PlanBoard/PlanBoard.swift
> +
오타 수정!
```suggestion
            case let .dragExceededSchedule(shiftedCol, exceededCol):
                state.shiftedCol += shiftedCol
                state.exceededCol += exceededCol
                return .none
                
```

2023-11-25 13:08 UTC, xnoag commented on gridy/Sources/ContentView.swift
> +//            ._printChanges()
기억이 잘 나지 않는데, 해킹 당했었나봐요. 수정하겠습니다.

2023-11-25 13:17 UTC, xnoag commented on gridy/Sources/ContentView.swift
> +//            ._printChanges()
8분 지나고 생각해보니까 재미도 없고 쓸데없는 변명이네요. 죄송합니다ㅠㅠ

2023-11-26 03:05 UTC, dayo2n commented on gridy/Sources/ContentView.swift
> +//            ._printChanges()
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 재밌는데 ㅋ

2023-11-26 04:09 UTC, xnoag commented on gridy/Sources/ContentView.swift
> +//            ._printChanges()
[fix][#88] printChange 주석 삭제

2023-11-26 04:12 UTC, xnoag commented on gridy/Sources/Models/SelectedScheduleRange.swift
> +    }
[fix][#88] startCol endCol 비교

2023-11-26 04:14 UTC, xnoag commented on gridy/Sources/Presentations/PlanBoard/PlanBoard.swift
> +        case dragExceededSchedule(shiftedCl: Int, exceededCol: Int)
[fix][#88] StartedCl -> StartedCol로 수정

2023-11-26 04:14 UTC, xnoag commented on gridy/Sources/Presentations/PlanBoard/PlanBoard.swift
> +
[fix][#88] StartedCl -> StartedCol로 수정

2023-11-26 04:15 UTC, xnoag commented
> 오타정도를 제외하고는 특별히 문제될만한 것들을 발견하지 못했습니다 새삼 기능 하나를 온전히 구현할 수 있을정도로 성장했음이 느껴져 대단하네요 물론 많은 도움을 줬을 릴리가 함께했지만~🌼 수고했습니다 가온 코멘트드린 것들만 수정해주시면 되겠습니다 단축키건에 대해서는 한번에 처리하도록 하겠습니다

감동이네요 김제나. 코드리뷰 반영해서 올렸습니다. 김제나의 밥그릇을 위협하는 김가온이 될게요.

2023-11-26 04:44 UTC, abovocado requested changes
고생했어요 가온~! 코드가 깔끔해서 (물론 제가 도와줬지만 ㅎ) 리뷰가 빨랐습니다!

기존의 연산이 많은 코드들이 func로 들어간 부분도 좋았어요!

뷰에서 남은 연산들은 나중에 한꺼번에 처리하면 좋을 것 같으니 그 부분은 이번 리뷰에서는 제외하고 봐주시면 감사하겠습니다. (코멘트는 달아놨어용)

로직에 문제가있기보단 이름 명명 등에 관한 부분에 몇 가지 제안사항이 있으니 확인해주시면 좋을 것 같아요~!~!~! ^0^

선물로 고래를 남겨놓고 갑니다!

._____________.

0_____________0

2023-11-26 04:44 UTC, abovocado commented on gridy/Sources/Presentations/PlanBoard/PlanBoard.swift
> +}
DragType이 영역별로 나뉘지 않아도 될 것 같은데 어떻게 생각하시나요?
저도 listArea에서 DragType을 사용하는데 기존의 것을 그대로 사용하고 있거든요.
영역별로 나뉘는게 아니라면, LineAreaDragType > DragType으로 이름을 바꿔서 같은 DragType을 사용하는 것도 좋을 것 같아요~!

2023-11-26 04:44 UTC, abovocado commented on gridy/Sources/Presentations/PlanBoard/PlanBoard.swift
> +        case dragGestureEndedScheduleArea(SelectedScheduleRange?)
case ...Schedule
case ...ScheduleArea 이렇게 끝나는데 case 가 끝나는게 통일되면 좋을 것 같네요~!

2023-11-26 04:44 UTC, abovocado commented on gridy/Sources/Presentations/PlanBoard/PlanBoardView.swift
> +                    scheduleItem(geometry: geometry)
오 이런 혁신적인,,,!

2023-11-26 04:44 UTC, abovocado commented on gridy/Sources/Presentations/PlanBoard/PlanBoardView.swift
> +                            let endCol = Int(dragEnd.x / viewStore.gridWidth)
여기서 상수에 연산 결과를 담는것을 나중에는 function으로 빼면 좋겠네요! 이건 나중에 한꺼번에 작업합시다!

2023-11-26 04:44 UTC, abovocado commented on gridy/Sources/Presentations/PlanBoard/PlanBoardView.swift
> +    }
이 이후에 모두 뷰를 return하는 함수들인데 @ViewBuilder를 사용하는 것을 권장한다고 합니다~!
https://developer.apple.com/videos/play/wwdc2021/10022/
참고하세용

2023-11-26 04:44 UTC, abovocado commented on gridy/Sources/Presentations/PlanBoard/PlanBoardView.swift
> +    }
@ViewBuilder를 붙여서 만든다면 암시적으로 해당 뷰 안에서만들어 사용하겠다는 뜻이라고 합니다~! 다른 view에서 사용하지 않는 view들이라면 struct로 선언하기보다 @viewBuilder가 붙은 func로 선언한다고 하네요~!

2023-11-26 04:45 UTC, xnoag commented on gridy/Sources/Presentations/PlanBoard/PlanBoardView.swift
> +                            let endCol = Int(dragEnd.x / viewStore.gridWidth)
네 ㅎ

2023-11-26 04:50 UTC, xnoag commented on gridy/Sources/Presentations/PlanBoard/PlanBoard.swift
> +}
<img width="357" alt="스크린샷 2023-11-26 오후 1 49 25" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team15-Ampersand/assets/125735850/a6ea8d18-97b7-488e-8923-07978aaa5900">

동의합니다~~ 반영해서 수정하겠습니다.

2023-11-26 04:52 UTC, xnoag commented on gridy/Sources/Presentations/PlanBoard/PlanBoard.swift
> +}
[fix][#88] DragType 통일

2023-11-26 04:57 UTC, xnoag commented on gridy/Sources/Presentations/PlanBoard/PlanBoard.swift
> +        case dragGestureEndedScheduleArea(SelectedScheduleRange?)
[fix][#88] ScheduleArea-Schedule case 통일

2023-11-26 05:20 UTC, abovocado approved these changes
빠른반영 감사!
쾌속선 한가온! SRT 한가온!

2023-11-26 05:21 UTC, merged